<?php

use Classes\PostgresMigration;

class M9930EsocialCargaHorarios extends PostgresMigration
{
    public function up()
    {
        $this->execute("
            UPDATE avaliacao SET db101_cargadados = 'SELECT x.instituicao, x.codigo, x.descricao, x.entrada, x.saida, x.duracaojornada - x.intervalo AS duracaojornada, x.intervalo FROM(SELECT instituicao, codigo, descricao, substring(replace(entrada::text,\':\', \'\'), 1, 4) AS entrada, substring(replace(saida::text,\':\', \'\'), 1, 4) AS saida, round(extract(epoch FROM (CASE WHEN (saida::time > entrada::time) THEN (saida - entrada)::time ELSE (((CURRENT_DATE || \' \'||saida)::TIMESTAMP + interval \'1 day\')::TIMESTAMP - (CURRENT_DATE || \' \'|| entrada)::TIMESTAMP)::time END)::time) / 60) AS duracaojornada, round(extract(epoch FROM (CASE WHEN (intervalo_fim::time > intervalo_inicio::time) THEN (intervalo_fim - intervalo_inicio)::time ELSE (((CURRENT_DATE || \' \'||intervalo_fim)::TIMESTAMP + interval \'1 day\')::TIMESTAMP - (CURRENT_DATE || \' \'|| intervalo_inicio)::TIMESTAMP)::time END)) / 60) AS intervalo FROM (SELECT DISTINCT fc_getsession(\'DB_instit\')::int AS instituicao, rh188_sequencial AS codigo, rh188_descricao AS descricao, (SELECT rh189_hora FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 1)::time AS entrada, (CASE WHEN (SELECT count(rh189_hora) FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 4 LIMIT 1) = 1 THEN (SELECT rh189_hora FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 4) ELSE (SELECT rh189_hora FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 2) END)::time AS saida, (CASE WHEN (SELECT count(rh189_hora) FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 4 LIMIT 1) = 1 THEN (SELECT rh189_hora FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 2) ELSE \'00:00\' END)::time AS intervalo_inicio, (CASE WHEN (SELECT count(rh189_hora) FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 4 LIMIT 1) = 1 THEN (SELECT rh189_hora FROM jornadahoras WHERE rh189_jornada = rh188_sequencial AND rh189_tiporegistro = 3) ELSE \'00:00\' END)::time AS intervalo_fim FROM jornada INNER JOIN jornadahoras ON rh188_sequencial = rh189_jornada GROUP BY codigo, descricao ORDER BY rh188_sequencial) AS y) AS x;' 
            WHERE db101_sequencial = 3000019 
        ");
    }

    public function down()
    {
        $this->execute("
            UPDATE avaliacao SET db101_cargadados = 'select instituicao, codigo, descricao, substring(replace(entrada::text,\':\', \'\'), 1, 4) as entrada, substring( replace(saida::text,\':\', \'\'), 1, 4) as saida, substring( replace(( case when (saida::time > entrada::time) then (saida - entrada)::time else (((current_date || \' \'||saida)::timestamp + interval \'1 day\')::timestamp - (current_date || \' \'|| entrada)::timestamp)::time end )::text,\':\', \'\'), 1, 4) as duracaojornada, substring( replace(( case when (intervalofim::time > intervaloinicio::time) then (intervalofim - intervaloinicio)::time else (((current_date || \' \'||intervalofim)::timestamp + interval \'1 day\')::timestamp - (current_date || \' \'|| intervaloinicio)::timestamp)::time end )::text,\':\', \'\'), 1, 4) as intervalo, substring(replace(intervaloinicio::text,\':\', \'\'), 1, 4) as intervaloinicio, substring(replace(intervalofim::text,\':\', \'\'), 1, 4) as intervalofim from ( SELECT distinct fc_getsession(\'DB_instit\')::int as instituicao, rh188_sequencial as codigo, rh188_descricao as descricao, (select rh189_hora from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 1)::time as entrada, (case when (select count(rh189_hora) from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 4 limit 1) = 1 then (select rh189_hora from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 4) else (select rh189_hora from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 2) END)::time AS saida, (case when (select count(rh189_hora) from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 4 limit 1) = 1 then (select rh189_hora from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 2) else \'00:00\' END)::time AS intervaloinicio, (case when (select count(rh189_hora) from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 4 limit 1) = 1 then (select rh189_hora from jornadahoras where rh189_jornada = rh188_sequencial and rh189_tiporegistro = 3) else \'00:00\' END)::time AS intervalofim FROM jornada INNER JOIN jornadahoras ON rh188_sequencial = rh189_jornada group by codigo, descricao ORDER BY rh188_sequencial) as x;' 
            WHERE db101_sequencial = 3000019
        ");
    }
}
