<?php

use Classes\PostgresMigration;

class M10548AnexoIvRgf extends PostgresMigration
{
    public function up()
    {
        $this->adicionaRelatorio();
        $this->adicionaLinhas();
        $this->adicionaConfiguracao();
        $this->adicionaColunas();
    }

    public function down()
    {
        $id = 185;
        $sql = <<<SQL
            delete from orcparamseqorcparamseqcoluna where o116_codparamrel = $id;
            delete from orcparamseqfiltropadrao      where o132_orcparamrel = $id;
            delete from orcparamseq                  where o69_codparamrel  = $id;
            delete from orcparamrelperiodos          where o113_orcparamrel = $id;
            delete from orcparamrel                  where o42_codparrel    = $id;
SQL;
        $this->execute($sql);
    }

    public function adicionaRelatorio()
    {
        $id  = 185;
        $sql = <<<SQL
            -- adiciona relatorio
            insert into orcparamrel values (185, 'RGF - ANEXO IV (2018)',  1, 'FONTE: Sistema E-Cidade, Unidade Responsável [nome_departamento], Data da emissão [data_emissao] e hora de emissão [hora_emissao]
1 Conforme Manual para Instrução de Pleitos (MIP), disponível em conteudo.tesouro.gov.br/manuais/mip, essas operações podem ser contratadas mesmo que não haja margem disponível nos limites. No entanto, uma vez contratadas, os fluxos de tais operações terão seus efeitos contabilizados para fins da contratação de outras operações de crédito.');

            -- adiciona periodos
            insert into orcparamrelperiodos VALUES (nextval('orcparamrelperiodos_o113_sequencial_seq'), 12, $id);
            insert into orcparamrelperiodos VALUES (nextval('orcparamrelperiodos_o113_sequencial_seq'), 13, $id);
            insert into orcparamrelperiodos VALUES (nextval('orcparamrelperiodos_o113_sequencial_seq'), 14, $id);
            insert into orcparamrelperiodos VALUES (nextval('orcparamrelperiodos_o113_sequencial_seq'), 15, $id);
            insert into orcparamrelperiodos VALUES (nextval('orcparamrelperiodos_o113_sequencial_seq'), 16, $id);
SQL;
        $this->execute($sql);
    }

    public function adicionaLinhas()
    {
        $sql = <<<SQL
            insert into orcparamseq values (185, 1, 'Mobiliária', 1, 1, 1, false, false, false, false, false, 'Mobiliária', false, true, 1, 1, '', false, 0);
            insert into orcparamseq values (185, 2, 'Interna', 1, 0, 1, false, false, false, false, false, 'Interna', true, false, 2, 2, '', false, 1);
            insert into orcparamseq values (185, 3, 'Externa', 1, 0, 1, false, false, false, false, false, 'Externa', true, false, 3, 2, '', false, 1);
            insert into orcparamseq values (185, 4, 'Contratual', 1, 1, 1, false, false, false, false, false, 'Contratual', false, true, 4, 1, '', false, 0);
            insert into orcparamseq values (185, 5, 'Interna', 1, 1, 1, false, false, false, false, false, 'Interna', false, true, 5, 2, '', false, 0);
            insert into orcparamseq values (185, 6, 'Empréstimos', 1, 0, 1, false, false, false, false, false, 'Empréstimos', true, false, 6, 3, '', false, 1);
            insert into orcparamseq values (185, 7, 'Aquisição Financiada de Bens e Arrendamento Mercantil Financ', 1, 0, 1, false, false, false, false, false, 'Aquisição Financiada de Bens e Arrendamento Mercantil Financeiro', true, false, 7, 3, '', false, 3);
            insert into orcparamseq values (185, 8, 'Antecipação de Receita pela Venda a Termo de Bens e Serviços', 1, 0, 1, false, false, false, false, false, 'Antecipação de Receita pela Venda a Termo de Bens e Serviços', true, false, 8, 3, '', false, 3);
            insert into orcparamseq values (185, 9, 'Assunção, Reconhecimento e Confissão de Dívidas (LRF, art. 2', 1, 0, 1, false, false, false, false, false, 'Assunção, Reconhecimento e Confissão de Dívidas (LRF, art. 29, § 1º)', true, false, 9, 3, '', false, 3);
            insert into orcparamseq values (185, 10, 'Operações de crédito previstas no art. 7º § 3º da RSF nº 43/', 1, 0, 1, false, false, false, false, false, 'Operações de crédito previstas no art. 7º § 3º da RSF nº 43/2001 1 (I)', true, false, 10, 3, '', false, 1);
            insert into orcparamseq values (185, 11, 'Externa', 1, 1, 1, false, false, false, false, false, 'Externa', false, true, 11, 2, '', false, 0);
            insert into orcparamseq values (185, 12, 'Empréstimos', 1, 0, 1, false, false, false, false, false, 'Empréstimos', true, false, 12, 3, '', false, 1);
            insert into orcparamseq values (185, 13, 'Aquisição Financiada de Bens e Arrendamento Mercantil Financ', 1, 0, 1, false, false, false, false, false, 'Aquisição Financiada de Bens e Arrendamento Mercantil Financeiro', true, false, 13, 3, '', false, 3);
            insert into orcparamseq values (185, 14, 'Antecipações de Receitas pela Venda a Termo de Bens e Serviç', 1, 0, 1, false, false, false, false, false, 'Antecipações de Receitas pela Venda a Termo de Bens e Serviços', true, false, 14, 3, '', false, 3);
            insert into orcparamseq values (185, 15, 'Assunção, Reconhecimento e Confissão de Dívidas (LRF, art. 2', 1, 0, 1, false, false, false, false, false, 'Assunção, Reconhecimento e Confissão de Dívidas (LRF, art. 29, § 1º)', true, false, 15, 3, '', false, 3);
            insert into orcparamseq values (185, 16, 'Operações de crédito previstas no art. 7º § 3º da RSF nº 43/', 1, 0, 1, false, false, false, false, false, 'Operações de crédito previstas no art. 7º § 3º da RSF nº 43/2001 1 (II)', true, false, 16, 3, '', false, 1);
            insert into orcparamseq values (185, 17, 'TOTAL (III)', 1, 1, 1, false, false, false, false, false, 'TOTAL (III)', false, true, 17, 1, '', false, 0);
            insert into orcparamseq values (185, 18, 'RECEITA CORRENTE LÍQUIDA - RCL (IV)', 1, 1, 1, false, false, false, false, false, 'RECEITA CORRENTE LÍQUIDA - RCL (IV)', false, true, 18, 1, '', false, 0);
            insert into orcparamseq values (185, 19, 'OPERAÇÕES VEDADAS (V)', 1, 0, 1, false, false, false, false, false, 'OPERAÇÕES VEDADAS (V)', true, false, 19, 1, '', false, 3);
            insert into orcparamseq values (185, 20, 'TOTAL CONSIDERADO PARA FINS DA APURAÇÃO DO CUMPRIMENTO DO LI', 1, 1, 1, false, false, false, false, false, 'TOTAL CONSIDERADO PARA FINS DA APURAÇÃO DO CUMPRIMENTO DO LIMITE (VI)= (IIIa + V - Ia - IIa)', false, true, 20, 1, '', false, 0);
            insert into orcparamseq values (185, 21, 'LIMITE GERAL DEFINIDO POR RESOLUÇÃO DO SENADO FEDERAL PARA A', 1, 1, 1, false, false, false, false, false, 'LIMITE GERAL DEFINIDO POR RESOLUÇÃO DO SENADO FEDERAL PARA AS OPERAÇÕES DE CRÉDITO INTERNAS E EXTERNAS', false, true, 21, 1, '', false, 0);
            insert into orcparamseq values (185, 22, 'LIMITE DE ALERTA (inciso III do §1º do art. 59 da LRF) ? 14.', 1, 1, 1, false, false, false, false, false, 'LIMITE DE ALERTA (inciso III do §1º do art. 59 da LRF) - 14.4%', false, true, 22, 1, '', false, 0);
            insert into orcparamseq values (185, 23, 'OPERAÇÕES DE CRÉDITO POR ANTECIPAÇÃO DA RECEITA ORÇAMENTÁRIA', 1, 0, 1, false, false, false, false, false, 'OPERAÇÕES DE CRÉDITO POR ANTECIPAÇÃO DA RECEITA ORÇAMENTÁRIA', true, false, 23, 1, '', false, 3);
            insert into orcparamseq values (185, 24, 'LIMITE DEFINIDO POR RESOLUÇÃO DO SENADO FEDERAL PARA AS OPER', 1, 1, 1, false, false, false, false, false, 'LIMITE DEFINIDO POR RESOLUÇÃO DO SENADO FEDERAL PARA AS OPERAÇÕES DE CRÉDITO POR ANTECIPAÇÃO DA RECEITA ORÇAMENTÁRIA', false, true, 24, 1, '', false, 0);
            insert into orcparamseq values (185, 25, 'Parcelamentos de Dívidas', 1, 1, 1, false, false, false, false, false, 'Parcelamentos de Dívidas', false, true, 25, 1, '', false, 0);
            insert into orcparamseq values (185, 26, 'Tributos', 1, 0, 1, false, false, false, false, false, 'Tributos', true, false, 26, 2, '', false, 3);
            insert into orcparamseq values (185, 27, 'Contribuições Previdenciárias', 1, 0, 1, false, false, false, false, false, 'Contribuições Previdenciárias', true, false, 27, 2, '', false, 3);
            insert into orcparamseq values (185, 28, 'FGTS', 1, 0, 1, false, false, false, false, false, 'FGTS', true, false, 28, 2, '', false, 3);
            insert into orcparamseq values (185, 29, 'Operações de reestruturação e recomposição do principal de d', 1, 0, 1, false, false, false, false, false, 'Operações de reestruturação e recomposição do principal de dívidas', true, false, 29, 1, '', false, 1);
SQL;
        $this->execute($sql);

    }
    

    public function adicionaConfiguracao()
    {
        $sql = <<<SQL
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 2, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?> <filter><contas><conta estrutural="421110011000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 3, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?> <filter><contas><conta estrutural="421210011000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 6, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?> <filter><contas><conta estrutural="421180111000000" nivel="" exclusao="false" /><conta estrutural="421180121000000" nivel="" exclusao="false" /><conta estrutural="421180131000000" nivel="" exclusao="false" /><conta estrutural="421180141000000" nivel="" exclusao="false" /><conta estrutural="421180171000000" nivel="" exclusao="false" /><conta estrutural="421120011000000" nivel="" exclusao="false" /><conta estrutural="421190011000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 7, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?> <filter><contas><conta estrutural="893110000000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 8, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?> <filter><contas><conta estrutural="893120000000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 9, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?> <filter><contas><conta estrutural="893130000000000" nivel="" exclusao="false" /><conta estrutural="853600000000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 10, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="421180151000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 12, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="421280111000000" nivel="" exclusao="false" /><conta estrutural="421280121000000" nivel="" exclusao="false" /><conta estrutural="421280131000000" nivel="" exclusao="false" /><conta estrutural="421280141000000" nivel="" exclusao="false" /><conta estrutural="421220011000000" nivel="" exclusao="false" /><conta estrutural="421290011000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 13, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="893210000000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 14, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="893220000000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 15, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="893230000000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 16, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="421280151000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 19, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="893400000000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 23, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="212110205000000" nivel="" exclusao="false" /><conta estrutural="212130205000000" nivel="" exclusao="false" /><conta estrutural="212140205000000" nivel="" exclusao="false" /><conta estrutural="212150205000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 26, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="893310100000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 27, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="893310200000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 28, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="893310300000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 185, 29, 2018, '<?xml version="1.0" encoding="ISO-8859-1"?><filter><contas><conta estrutural="421110021000000" nivel="" exclusao="false" /><conta estrutural="421180161000000" nivel="" exclusao="false" /><conta estrutural="421210021000000" nivel="" exclusao="false" /><conta estrutural="421280161000000" nivel="" exclusao="false" /></contas><orgao operador="in" valor="" id="orgao"/><unidade operador="in" valor="" id="unidade"/><funcao operador="in" valor="" id="funcao"/><subfuncao operador="in" valor="" id="subfuncao"/><programa operador="in" valor="" id="programa"/><projativ operador="in" valor="" id="projativ"/><recurso operador="in" valor="" id="recurso"/><recursocontalinha numerolinha="" id="recursocontalinha"/><observacao valor=""/><desdobrarlinha valor="false"/></filter>');
SQL;
        $this->execute($sql);
    }

    public function adicionaColunas()
    {
        $sql = <<<SQL
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 217, 1, 12, 'L[2]->noperiodo+L[3]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 217, 1, 13, 'L[2]->noperiodo+L[3]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 217, 1, 14, 'L[2]->noperiodo+L[3]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 217, 1, 15, 'L[2]->noperiodo+L[3]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 217, 1, 16, 'L[2]->noperiodo+L[3]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 218, 2, 12, 'L[2]->ateperiodo+L[3]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 218, 2, 13, 'L[2]->ateperiodo+L[3]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 218, 2, 14, 'L[2]->ateperiodo+L[3]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 218, 2, 15, 'L[2]->ateperiodo+L[3]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 185, 218, 2, 16, 'L[2]->ateperiodo+L[3]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 217, 1, 12, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 217, 1, 13, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 217, 1, 14, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 217, 1, 15, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 217, 1, 16, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 218, 2, 12, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 218, 2, 13, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 218, 2, 14, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 218, 2, 15, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 185, 218, 2, 16, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 217, 1, 12, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 217, 1, 13, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 217, 1, 14, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 217, 1, 15, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 217, 1, 16, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 218, 2, 12, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 218, 2, 13, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 218, 2, 14, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 218, 2, 15, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 185, 218, 2, 16, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 217, 1, 12, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 217, 1, 13, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 217, 1, 14, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 217, 1, 15, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 217, 1, 16, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 218, 2, 12, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 218, 2, 13, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 218, 2, 14, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 218, 2, 15, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 185, 218, 2, 16, 'F[5]+F[11]');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 217, 1, 12, 'L[6]->noperiodo+L[7]->noperiodo+L[8]->noperiodo+L[9]->noperiodo+L[10]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 217, 1, 13, 'L[6]->noperiodo+L[7]->noperiodo+L[8]->noperiodo+L[9]->noperiodo+L[10]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 217, 1, 14, 'L[6]->noperiodo+L[7]->noperiodo+L[8]->noperiodo+L[9]->noperiodo+L[10]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 217, 1, 15, 'L[6]->noperiodo+L[7]->noperiodo+L[8]->noperiodo+L[9]->noperiodo+L[10]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 217, 1, 16, 'L[6]->noperiodo+L[7]->noperiodo+L[8]->noperiodo+L[9]->noperiodo+L[10]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 218, 2, 12, 'L[6]->ateperiodo+L[7]->ateperiodo+L[8]->ateperiodo+L[9]->ateperiodo+L[10]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 218, 2, 13, 'L[6]->ateperiodo+L[7]->ateperiodo+L[8]->ateperiodo+L[9]->ateperiodo+L[10]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 218, 2, 14, 'L[6]->ateperiodo+L[7]->ateperiodo+L[8]->ateperiodo+L[9]->ateperiodo+L[10]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 218, 2, 15, 'L[6]->ateperiodo+L[7]->ateperiodo+L[8]->ateperiodo+L[9]->ateperiodo+L[10]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 185, 218, 2, 16, 'L[6]->ateperiodo+L[7]->ateperiodo+L[8]->ateperiodo+L[9]->ateperiodo+L[10]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 217, 1, 12, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 217, 1, 13, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 217, 1, 14, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 217, 1, 15, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 217, 1, 16, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 218, 2, 12, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 218, 2, 13, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 218, 2, 14, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 218, 2, 15, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 185, 218, 2, 16, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 217, 1, 12, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 217, 1, 13, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 217, 1, 14, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 217, 1, 15, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 217, 1, 16, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 218, 2, 12, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 218, 2, 13, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 218, 2, 14, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 218, 2, 15, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 185, 218, 2, 16, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 217, 1, 12, 'L[12]->noperiodo+L[13]->noperiodo+L[14]->noperiodo+L[15]->noperiodo+L[16]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 217, 1, 13, 'L[12]->noperiodo+L[13]->noperiodo+L[14]->noperiodo+L[15]->noperiodo+L[16]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 217, 1, 14, 'L[12]->noperiodo+L[13]->noperiodo+L[14]->noperiodo+L[15]->noperiodo+L[16]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 217, 1, 15, 'L[12]->noperiodo+L[13]->noperiodo+L[14]->noperiodo+L[15]->noperiodo+L[16]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 217, 1, 16, 'L[12]->noperiodo+L[13]->noperiodo+L[14]->noperiodo+L[15]->noperiodo+L[16]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 218, 2, 12, 'L[12]->ateperiodo+L[13]->ateperiodo+L[14]->ateperiodo+L[15]->ateperiodo+L[16]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 218, 2, 13, 'L[12]->ateperiodo+L[13]->ateperiodo+L[14]->ateperiodo+L[15]->ateperiodo+L[16]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 218, 2, 14, 'L[12]->ateperiodo+L[13]->ateperiodo+L[14]->ateperiodo+L[15]->ateperiodo+L[16]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 218, 2, 15, 'L[12]->ateperiodo+L[13]->ateperiodo+L[14]->ateperiodo+L[15]->ateperiodo+L[16]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 185, 218, 2, 16, 'L[12]->ateperiodo+L[13]->ateperiodo+L[14]->ateperiodo+L[15]->ateperiodo+L[16]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 217, 1, 12, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 217, 1, 13, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 217, 1, 14, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 217, 1, 15, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 217, 1, 16, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 218, 2, 12, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 218, 2, 13, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 218, 2, 14, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 218, 2, 15, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 185, 218, 2, 16, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 15, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 217, 1, 12, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 217, 1, 13, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 217, 1, 14, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 217, 1, 15, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 217, 1, 16, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 218, 2, 12, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 218, 2, 13, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 218, 2, 14, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 218, 2, 15, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 16, 185, 218, 2, 16, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 217, 1, 12, 'L[1]->noperiodo+L[4]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 217, 1, 13, 'L[1]->noperiodo+L[4]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 217, 1, 14, 'L[1]->noperiodo+L[4]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 217, 1, 15, 'L[1]->noperiodo+L[4]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 217, 1, 16, 'L[1]->noperiodo+L[4]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 218, 2, 12, 'L[1]->ateperiodo+L[4]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 218, 2, 13, 'L[1]->ateperiodo+L[4]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 218, 2, 14, 'L[1]->ateperiodo+L[4]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 218, 2, 15, 'L[1]->ateperiodo+L[4]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 17, 185, 218, 2, 16, 'L[1]->ateperiodo+L[4]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 36, 1, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 36, 1, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 36, 1, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 36, 1, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 36, 1, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 222, 2, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 222, 2, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 222, 2, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 222, 2, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 18, 185, 222, 2, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 36, 1, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 36, 1, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 36, 1, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 36, 1, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 36, 1, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 222, 2, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 222, 2, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 222, 2, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 222, 2, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 19, 185, 222, 2, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 36, 1, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 36, 1, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 36, 1, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 36, 1, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 36, 1, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 222, 2, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 222, 2, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 222, 2, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 222, 2, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 20, 185, 222, 2, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 36, 1, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 36, 1, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 36, 1, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 36, 1, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 36, 1, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 222, 2, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 222, 2, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 222, 2, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 222, 2, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 21, 185, 222, 2, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 36, 1, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 36, 1, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 36, 1, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 36, 1, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 36, 1, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 222, 2, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 222, 2, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 222, 2, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 222, 2, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 22, 185, 222, 2, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 36, 1, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 36, 1, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 36, 1, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 36, 1, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 36, 1, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 222, 2, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 222, 2, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 222, 2, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 222, 2, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 23, 185, 222, 2, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 36, 1, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 36, 1, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 36, 1, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 36, 1, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 36, 1, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 222, 2, 12, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 222, 2, 13, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 222, 2, 14, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 222, 2, 15, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 24, 185, 222, 2, 16, '');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 217, 1, 12, 'L[26]->noperiodo+L[27]->noperiodo+L[28]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 217, 1, 13, 'L[26]->noperiodo+L[27]->noperiodo+L[28]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 217, 1, 14, 'L[26]->noperiodo+L[27]->noperiodo+L[28]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 217, 1, 15, 'L[26]->noperiodo+L[27]->noperiodo+L[28]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 217, 1, 16, 'L[26]->noperiodo+L[27]->noperiodo+L[28]->noperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 218, 2, 12, 'L[26]->ateperiodo+L[27]->ateperiodo+L[28]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 218, 2, 13, 'L[26]->ateperiodo+L[27]->ateperiodo+L[28]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 218, 2, 14, 'L[26]->ateperiodo+L[27]->ateperiodo+L[28]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 218, 2, 15, 'L[26]->ateperiodo+L[27]->ateperiodo+L[28]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 25, 185, 218, 2, 16, 'L[26]->ateperiodo+L[27]->ateperiodo+L[28]->ateperiodo');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 26, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 27, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 217, 1, 12, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 217, 1, 13, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 217, 1, 14, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 217, 1, 15, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 217, 1, 16, '#saldo_anterior_credito - #saldo_anterior_debito');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 218, 2, 12, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 218, 2, 13, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 218, 2, 14, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 218, 2, 15, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 28, 185, 218, 2, 16, '(in_array(substr(#estrutural, 0, 1), array(1, 3, 5, 7)) && #sinal_final == "C") || (in_array(substr(#estrutural, 0, 1), array(2, 4, 6, 8)) && #sinal_final == "D") ? #saldo_final *= -1 : #saldo_final');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 217, 1, 12, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 217, 1, 13, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 217, 1, 14, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 217, 1, 15, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 217, 1, 16, '#saldo_arrecadado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 218, 2, 12, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 218, 2, 13, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 218, 2, 14, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 218, 2, 15, '#saldo_arrecadado_acumulado');
            insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 29, 185, 218, 2, 16, '#saldo_arrecadado_acumulado');
SQL;
        $this->execute($sql);
    }
}
