<?php

use Classes\PostgresMigration;

class M10220RreoAnexoIii extends PostgresMigration
{
    public function up()
    {
        $sSql = "
                insert into orcparamrel ( o42_codparrel, o42_descrrel, o42_orcparamrelgrupo, o42_notapadrao) values (178, 'ANEXO III (RREO - 2018)', 1, 'Fonte: Sistema E-Cidade, Unidade Responsável [nome_departamento], Data de emissão [data_emissao] e hora de emissão [hora_emissao]');
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 6 , 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 7 , 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 8 , 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 9 , 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 10, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 11, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 17, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 18, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 19, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 20, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 21, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 22, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 23, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 24, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 25, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 26, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 27, 178);
                insert into orcparamrelperiodos (o113_sequencial, o113_periodo, o113_orcparamrel) values (nextval('orcparamrelperiodos_o113_sequencial_seq'), 28, 178);


                insert into orcparamseq values (178, 1, 'IPTU', 1, 0, 1, false, false, false, false, false, 'IPTU', true, false, 3, 3, '', false, 1);
                insert into orcparamseq values (178, 2, 'ISS', 1, 0, 1, false, false, false, false, false, 'ISS', true, false, 4, 3, '', false, 1);
                insert into orcparamseq values (178, 3, 'ITBI', 1, 0, 1, false, false, false, false, false, 'ITBI', true, false, 5, 3, '', false, 1);
                insert into orcparamseq values (178, 4, 'IRRF', 1, 0, 1, false, false, false, false, false, 'IRRF', true, false, 6, 3, '', false, 1);
                insert into orcparamseq values (178, 5, 'Outros Impostos, Taxas e Contribuições de Melhoria', 1, 0, 1, false, false, false, false, false, 'Outros Impostos, Taxas e Contribuições de Melhoria', true, false, 7, 3, '', false, 1);
                insert into orcparamseq values (178, 6, 'Contribuições', 1, 0, 1, false, false, false, false, false, 'Contribuições', true, false, 8, 2, '', false, 1);
                insert into orcparamseq values (178, 7, 'Rendimentos de Aplicação Financeira', 1, 0, 1, false, false, false, false, false, 'Rendimentos de Aplicação Financeira', true, false, 10, 3, '', false, 1);
                insert into orcparamseq values (178, 8, 'Outras Receitas Patrimoniais', 1, 0, 1, false, false, false, false, false, 'Outras Receitas Patrimoniais', true, false, 11, 3, '', false, 1);
                insert into orcparamseq values (178, 9, 'Receita Agropecuária', 1, 0, 1, false, false, false, false, false, 'Receita Agropecuária', true, false, 12, 2, '', false, 1);
                insert into orcparamseq values (178, 10, 'Receita Industrial', 1, 0, 1, false, false, false, false, false, 'Receita Industrial', true, false, 13, 2, '', false, 1);
                insert into orcparamseq values (178, 11, 'Receita de Serviços', 1, 0, 1, false, false, false, false, false, 'Receita de Serviços', true, false, 14, 2, '', false, 1);
                insert into orcparamseq values (178, 12, 'Cota-Parte do FPM', 1, 0, 1, false, false, false, false, false, 'Cota-Parte do FPM', true, false, 16, 3, '', false, 1);
                insert into orcparamseq values (178, 13, 'Cota-Parte do ICMS', 1, 0, 1, false, false, false, false, false, 'Cota-Parte do ICMS', true, false, 17, 3, '', false, 1);
                insert into orcparamseq values (178, 14, 'Cota-Parte do IPVA', 1, 0, 1, false, false, false, false, false, 'Cota-Parte do IPVA', true, false, 18, 3, '', false, 1);
                insert into orcparamseq values (178, 15, 'Cota-Parte do ITR', 1, 0, 1, false, false, false, false, false, 'Cota-Parte do ITR', true, false, 19, 3, '', false, 1);
                insert into orcparamseq values (178, 16, 'Transferências da LC 87/1996', 1, 0, 1, false, false, false, false, false, 'Transferências da LC 87/1996', true, false, 20, 3, '', false, 1);
                insert into orcparamseq values (178, 17, 'Transferências da LC 61/1989', 1, 0, 1, false, false, false, false, false, 'Transferências da LC 61/1989', true, false, 21, 3, '', false, 1);
                insert into orcparamseq values (178, 18, 'Transferências do FUNDEB', 1, 0, 1, false, false, false, false, false, 'Transferências do FUNDEB', true, false, 22, 3, '', false, 1);
                insert into orcparamseq values (178, 19, 'Outras Transferências Correntes', 1, 0, 1, false, false, false, false, false, 'Outras Transferências Correntes', true, false, 23, 3, '', false, 1);
                insert into orcparamseq values (178, 20, 'Outras Receitas Correntes', 1, 0, 1, false, false, false, false, false, 'Outras Receitas Correntes', true, false, 24, 3, '', false, 1);
                insert into orcparamseq values (178, 21, 'Contrib. do Servidor para o Plano de Previdência', 1, 0, 1, false, false, false, false, false, 'Contrib. do Servidor para o Plano de Previdência', true, false, 26, 2, '', false, 1);
                insert into orcparamseq values (178, 22, 'Compensação Financ. entre Regimes Previdência', 1, 0, 1, false, false, false, false, false, 'Compensação Financ. entre Regimes Previdência', true, false, 27, 2, '', false, 1);
                insert into orcparamseq values (178, 23, 'Dedução de Receita para Formação do FUNDEB', 1, 0, 1, false, false, false, false, false, 'Dedução de Receita para Formação do FUNDEB', true, false, 28, 2, '', false, 1);

                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 1, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"411180110000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 2, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"411180230000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 3, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"411180140000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 4, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"411130310000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"411130340000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 5, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"411000000000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"411180110000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"411180230000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"411180140000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"411130310000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"411130340000000\" nivel=\"\" exclusao=\"true\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 6, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"412000000000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 7, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"413210010000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"413210020000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"413210030000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"413210040000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"413210050000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"413290010000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 8, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"413000000000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"413210010000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"413210020000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"413210030000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"413210040000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"413210050000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"413290010000000\" nivel=\"\" exclusao=\"true\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 9, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"414000000000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 10, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"415000000000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 11, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"416000000000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 12, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417180120000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"417180130000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"417180140000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 13, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417280110000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 14, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417280120000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 15, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417180150000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 16, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417180610000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 17, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417180160000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 18, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417580100000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 19, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"417000000000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"417180120000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417180130000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417180140000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417280110000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417280120000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417180150000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417180610000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417180160000000\" nivel=\"\" exclusao=\"true\" /><conta estrutural=\"417580100000000\" nivel=\"\" exclusao=\"true\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 20, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"419000000000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 21, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"412100420000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"412100430000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"412100440000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"412100460000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"412100470000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"412100480000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 22, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"412100410000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"412100450000000\" nivel=\"\" exclusao=\"false\" /><conta estrutural=\"419900310000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
                insert into orcparamseqfiltropadrao values(nextval('orcparamelementospadrao_o132_sequencial_seq'), 178, 23, 2018, '<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><filter><contas><conta estrutural=\"917000000000000\" nivel=\"\" exclusao=\"false\" /></contas><orgao operador=\"in\" valor=\"\" id=\"orgao\"/><unidade operador=\"in\" valor=\"\" id=\"unidade\"/><funcao operador=\"in\" valor=\"\" id=\"funcao\"/><subfuncao operador=\"in\" valor=\"\" id=\"subfuncao\"/><programa operador=\"in\" valor=\"\" id=\"programa\"/><projativ operador=\"in\" valor=\"\" id=\"projativ\"/><recurso operador=\"in\" valor=\"\" id=\"recurso\"/><recursocontalinha numerolinha=\"\" id=\"recursocontalinha\"/><observacao valor=\"\"/><desdobrarlinha valor=\"false\"/></filter>');
            ";
        $this->execute($sSql);
    }

    public function down()
    {
        $sSql = "
            delete from orcparamseqfiltroorcamento where o133_orcparamrel = 178;
            delete from orcparamrelperiodos where o113_orcparamrel = 178;
            delete from orcparamseqfiltropadrao where o132_orcparamrel = 178;
            delete from orcparamseq where o69_codparamrel = 178;
            delete from orcparamrel where o42_codparrel = 178;
        ";
        $this->execute($sSql);
    }
}
