<?php

use Classes\PostgresMigration;

class M15300Anexo1 extends PostgresMigration
{

    public function down()
    {

        $this->execute(<<<SQL_DOWN

delete from orcparamseqorcparamseqcoluna where o116_codparamrel = 206;
delete from orcparamseq where o69_codparamrel = 206;


SQL_DOWN
);

    }

    public function up()
    {
        $this->execute(<<<SQL_UP

insert into orcparamseq values (206,  1, 'IPTU', 1, 0, 0, false, false, false, false, false, 'IPTU', false, false, 1, 0, '', false, 1);
insert into orcparamseq values (206,  2, 'IRRF', 1, 0, 0, false, false, false, false, false, 'IRRF', false, false, 2, 0, '', false, 1);
insert into orcparamseq values (206,  3, 'ITBI', 1, 0, 0, false, false, false, false, false, 'ITBI', false, false, 3, 0, '', false, 1);
insert into orcparamseq values (206,  4, 'ISSQN', 1, 0, 0, false, false, false, false, false, 'ISSQN', false, false, 4, 0, '', false, 1);
insert into orcparamseq values (206,  5, 'FPM', 1, 0, 0, false, false, false, false, false, 'FPM', false, false, 5, 0, '', false, 1);
insert into orcparamseq values (206,  6, 'ITR', 1, 0, 0, false, false, false, false, false, 'ITR', false, false, 6, 0, '', false, 1);
insert into orcparamseq values (206,  7, 'Cota Ouro', 1, 0, 0, false, false, false, false, false, 'Cota Ouro', false, false, 7, 0, '', false, 1);
insert into orcparamseq values (206,  8, 'ICMS-Desoneração LC 87/96-Lei Kandir', 1, 0, 0, false, false, false, false, false, 'ICMS-Desoneração LC 87/96-Lei Kandir', false, false, 8, 0, '', false, 1);
insert into orcparamseq values (206,  9, 'ICMS', 1, 0, 0, false, false, false, false, false, 'ICMS', false, false, 9, 0, '', false, 1);
insert into orcparamseq values (206, 10, 'IPVA', 1, 0, 0, false, false, false, false, false, 'IPVA', false, false, 10, 0, '', false, 1);
insert into orcparamseq values (206, 11, 'IPI s/ Exportação', 1, 0, 0, false, false, false, false, false, 'IPI s/ Exportação', false, false, 11, 0, '', false, 1);
insert into orcparamseq values (206, 12, 'Dívida Ativa de Impostos', 1, 0, 0, false, false, false, false, false, 'Dívida Ativa de Impostos', false, false, 12, 0, '', false, 1);
insert into orcparamseq values (206, 13, 'Multa e Juros s/ impostos', 1, 0, 0, false, false, false, false, false, 'Multa e Juros s/ impostos', false, false, 13, 0, '', false, 1);
insert into orcparamseq values (206, 14, '8. RECEITA TOTAL', 1, 0, 0, false, false, false, false, false, '8. RECEITA TOTAL', false, true, 14, 0, '', false, 0);

update orcparamseq set o69_manual = true where o69_codparamrel = 206 and o69_codseq <= 13;



insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 28, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 17, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 18, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 19, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 20, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 21, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 22, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 23, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 24, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 25, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 26, 'L[1]->mes / L[1]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 1, 206,   36,  3, 27, 'L[1]->mes / L[1]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 28, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 17, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 18, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 19, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 20, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 21, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 22, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 23, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 24, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 25, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 26, 'L[2]->mes / L[2]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 2, 206,   36,  3, 27, 'L[2]->mes / L[2]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 28, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 17, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 18, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 19, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 20, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 21, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 22, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 23, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 24, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 25, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 26, 'L[3]->mes / L[3]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 3, 206,   36,  3, 27, 'L[3]->mes / L[3]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 28, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 17, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 18, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 19, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 20, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 21, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 22, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 23, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 24, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 25, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 26, 'L[4]->mes / L[4]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 4, 206,   36,  3, 27, 'L[4]->mes / L[4]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 28, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 17, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 18, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 19, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 20, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 21, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 22, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 23, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 24, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 25, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 26, 'L[5]->mes / L[5]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 5, 206,   36,  3, 27, 'L[5]->mes / L[5]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 28, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 17, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 18, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 19, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 20, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 21, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 22, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 23, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 24, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 25, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 26, 'L[6]->mes / L[6]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 6, 206,   36,  3, 27, 'L[6]->mes / L[6]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 28, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 17, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 18, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 19, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 20, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 21, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 22, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 23, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 24, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 25, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 26, 'L[7]->mes / L[7]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 7, 206,   36,  3, 27, 'L[7]->mes / L[7]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 28, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 17, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 18, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 19, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 20, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 21, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 22, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 23, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 24, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 25, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 26, 'L[8]->mes / L[8]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 8, 206,   36,  3, 27, 'L[8]->mes / L[8]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 28, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 17, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 18, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 19, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 20, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 21, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 22, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 23, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 24, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 25, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 26, 'L[9]->mes / L[9]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 9, 206,   36,  3, 27, 'L[9]->mes / L[9]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 28, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 17, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 18, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 19, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 20, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 21, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 22, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 23, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 24, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 25, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 26, 'L[10]->mes / L[10]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 10, 206,   36,  3, 27, 'L[10]->mes / L[10]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 28, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 17, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 18, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 19, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 20, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 21, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 22, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 23, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 24, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 25, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 26, 'L[11]->mes / L[11]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 11, 206,   36,  3, 27, 'L[11]->mes / L[11]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 28, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 17, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 18, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 19, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 20, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 21, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 22, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 23, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 24, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 25, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 26, 'L[12]->mes / L[12]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 12, 206,   36,  3, 27, 'L[12]->mes / L[12]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 17, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 18, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 19, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 20, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 21, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 22, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 28, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 23, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 24, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 25, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 26, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  141,  1, 27, '#saldo_arrecadado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 22, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 28, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 27, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 26, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 25, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 24, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 23, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 21, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 20, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 19, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 18, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,  191,  2, 17, '#saldo_arrecadado_acumulado');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 28, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 17, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 18, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 19, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 20, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 21, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 22, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 23, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 24, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 25, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 26, 'L[13]->mes / L[13]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 13, 206,   36,  3, 27, 'L[13]->mes / L[13]->ano * 100');


insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 17, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 18, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 19, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 20, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 21, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 22, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 28, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 23, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 24, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 25, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 26, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  141,  1, 27, 'L[1]->mes+L[2]->mes+L[3]->mes+L[4]->mes+L[5]->mes+L[6]->mes+L[7]->mes+L[8]->mes+L[9]->mes+L[10]->mes+L[11]->mes+L[12]->mes+L[13]->mes');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 22, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 28, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 27, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 26, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 25, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 24, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 23, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 21, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 20, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 19, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 18, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,  191,  2, 17, 'L[1]->ano+L[2]->ano+L[3]->ano+L[4]->ano+L[5]->ano+L[6]->ano+L[7]->ano+L[8]->ano+L[9]->ano+L[10]->ano+L[11]->ano+L[12]->ano+L[13]->ano');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 28, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 17, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 18, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 19, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 20, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 21, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 22, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 23, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 24, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 25, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 26, 'L[14]->mes/L[14]->ano * 100');
insert into orcparamseqorcparamseqcoluna values (nextval('orcparamseqorcparamseqcoluna_o116_sequencial_seq'), 14, 206,   36,  3, 27, 'L[14]->mes/L[14]->ano * 100');


SQL_UP
);
    }
}
