<?php

use Classes\PostgresMigration;

class M18962HelpersProtocolo extends PostgresMigration
{
    public function up()
    {
        $this->execute("
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_de_municipio.md' WHERE id_item = 8302;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_de_municipio.md' WHERE id_item = 8303;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_de_estado.md' WHERE id_item = 8298;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_de_estado.md' WHERE id_item = 8299;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_logradouro.md' WHERE id_item = 5718;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_logradouro.md' WHERE id_item = 5719;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_logradouro.md' WHERE id_item = 5720;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_localidade.md' WHERE id_item = 5714;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_localidade.md' WHERE id_item = 5715;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_localidade.md' WHERE id_item = 5716;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_de_estado.md' WHERE id_item = 2291;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_de_estado.md' WHERE id_item = 2292;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_de_estado.md' WHERE id_item = 2293;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_cep.md' WHERE id_item = 2284;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_cep.md' WHERE id_item = 2285;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_cep.md' WHERE id_item = 2286;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_tipo_de_processo.md' WHERE id_item = 7851;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_tipo_de_processo.md' WHERE id_item = 7852;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_tipo_de_processo.md' WHERE id_item = 7853;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_tipo_de_processo_receita.md' WHERE id_item = 1707;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_tipo_de_processo_receita.md' WHERE id_item = 1708;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_tipo_de_processo_receita.md' WHERE id_item = 1709;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_documento.md' WHERE id_item = 2149;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_documento.md' WHERE id_item = 2150;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_documento.md' WHERE id_item = 2151;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_documento_tipo_de_processo.md' WHERE id_item = 2152;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_variavel.md' WHERE id_item = 2145;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_variavel.md' WHERE id_item = 2146;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_variavel.md' WHERE id_item = 2147;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_geral_do_municipio.md' WHERE id_item = 8452;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_geral_do_municipio.md' WHERE id_item = 8453;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_geral_do_municipio.md' WHERE id_item = 8454;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!cadastros_tipo_de_documento.md' WHERE id_item = 228316;
            UPDATE db_itensmenu SET help = ' https://e-cidade.wiki.br/patrimonial/protocolo/#!consultas_geral_financeira.md' WHERE id_item = 56;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!consultas_processo.md' WHERE id_item = 9227;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!consultas_cgm.md' WHERE id_item = 9255;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!consultas_cgm_duplo_processado.md' WHERE id_item = 8770;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_andamento_padrao.md' WHERE id_item = 2160;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_processos_departamento.md' WHERE id_item = 3781;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_cgms_correto.md' WHERE id_item = 3786;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_processos_cgm.md' WHERE id_item = 3791;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_variaveis.md' WHERE id_item = 3806;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_documentos.md' WHERE id_item = 3807;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_tipos_de_processo.md' WHERE id_item = 3812;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_documentos_tipo_de_processos.md' WHERE id_item = 3883;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_duplos_no_cgm.md' WHERE id_item = 3909;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_reimpressao_da_capa_de_processo.md' WHERE id_item = 3475;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_reimpressao_termo_de_transferencia.md' WHERE id_item = 2541;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_processos.md' WHERE id_item = 4073;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_consistencias_cpf_cnpj.md' WHERE id_item = 4155;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_etiquetas_para_processos.md' WHERE id_item = 9982;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_etiquetas_para_processos.md' WHERE id_item = 9983;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_processos_por_departamento.md' WHERE id_item = 4384;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_cgms_incluidos_alterados.md' WHERE id_item = 29323;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!relatorios_tipos_de_processos_com_receita.md' WHERE id_item = 437508;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_cgm_duplos.md' WHERE id_item = 2523;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_cgm_duplos.md' WHERE id_item = 2525;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_processos.md' WHERE id_item = 2163;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_processos.md' WHERE id_item = 2164;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_processos.md' WHERE id_item = 9852;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_volumes.md' WHERE id_item = 228322;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_volumes.md' WHERE id_item = 228323;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_volumes.md' WHERE id_item = 228324;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_tramite_inicial.md' WHERE id_item = 2181;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_despacho.md' WHERE id_item = 608572;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_despacho.md' WHERE id_item = 4196;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_transferencias.md' WHERE id_item = 2175;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_transferencias.md' WHERE id_item = 4124;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_recebimentos.md' WHERE id_item = 2182;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_arquivamento.md' WHERE id_item = 2184;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_arquivamento.md' WHERE id_item = 2185;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_arquivamento.md' WHERE id_item = 4257;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_desarquivamento.md' WHERE id_item = 3435;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_andamento_padrao.md' WHERE id_item = 2136;
            UPDATE db_itensmenu SET help = ' https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_recibo_de_receita.md' WHERE id_item = 111;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_cancela_recibo.md' WHERE id_item = 3809;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_tramite_interno.md' WHERE id_item = 4079;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_tramite_interno.md' WHERE id_item = 4083;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_tramite_interno.md' WHERE id_item = 4131;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_tramite_interno.md' WHERE id_item = 4098;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_apensar_processo.md' WHERE id_item = 9224;
            UPDATE db_itensmenu SET help =	'https://e-cidade.wiki.br/patrimonial/protocolo/#!procedimentos_andamento_do_processo.md' WHERE id_item = 228068;
        ");

    }

    public function down()
    {
        $this->execute("
            UPDATE db_itensmenu SET help = 'Consulta de Processo' WHERE id_item = 9227;
            UPDATE db_itensmenu SET help = 'Geral Financeira' WHERE id_item = 56;
            UPDATE db_itensmenu SET help = 'Recibo de Receita' WHERE id_item = 111;
            UPDATE db_itensmenu SET help = 'valor da receita do processo' WHERE id_item = 1707;
            UPDATE db_itensmenu SET help = 'Alteração' WHERE id_item = 1708;
            UPDATE db_itensmenu SET help = 'Exclusão do valor da receita' WHERE id_item = 1709;
            UPDATE db_itensmenu SET help = 'Andamento Padrão' WHERE id_item = 2136;
            UPDATE db_itensmenu SET help = 'Inclusão' WHERE id_item = 2145;
            UPDATE db_itensmenu SET help = 'Alteração' WHERE id_item = 2146;
            UPDATE db_itensmenu SET help = 'Exclusão' WHERE id_item = 2147;
            UPDATE db_itensmenu SET help = 'Inclusão' WHERE id_item = 2149;
            UPDATE db_itensmenu SET help = 'Alteração' WHERE id_item = 2150;
            UPDATE db_itensmenu SET help = 'Exclusão' WHERE id_item = 2151;
            UPDATE db_itensmenu SET help = 'Documento / Tipo de Processo' WHERE id_item = 2152;
            UPDATE db_itensmenu SET help = 'Relatório de Andamento Padrão' WHERE id_item = 2160;
            UPDATE db_itensmenu SET help = 'Inclusão' WHERE id_item = 2163;
            UPDATE db_itensmenu SET help = 'Alteração' WHERE id_item = 2164;
            UPDATE db_itensmenu SET help = 'Inclusão' WHERE id_item = 2175;
            UPDATE db_itensmenu SET help = 'Trâmite Inicial' WHERE id_item = 2181;
            UPDATE db_itensmenu SET help = 'Recebimento' WHERE id_item = 2182;
            UPDATE db_itensmenu SET help = 'Inclusão' WHERE id_item = 2184;
            UPDATE db_itensmenu SET help = 'Alteração' WHERE id_item = 2185;
            UPDATE db_itensmenu SET help = 'Inclusão de Db_ceplog' WHERE id_item = 2284;
            UPDATE db_itensmenu SET help = 'Alteração de Db_ceplog' WHERE id_item = 2285;
            UPDATE db_itensmenu SET help = 'Exclusão de Db_ceplog' WHERE id_item = 2286;
            UPDATE db_itensmenu SET help = 'Inclusão de Db_uf' WHERE id_item = 2291;
            UPDATE db_itensmenu SET help = 'Alteração de Db_uf' WHERE id_item = 2292;
            UPDATE db_itensmenu SET help = 'Exclusão de Db_uf' WHERE id_item = 2293;
            UPDATE db_itensmenu SET help = 'Inclusão' WHERE id_item = 2523;
            UPDATE db_itensmenu SET help = 'Exclusão de Cgmcorreto' WHERE id_item = 2525;
            UPDATE db_itensmenu SET help = 'Reimpressão do termo de transferencia de Transferência' WHERE id_item = 2541;
            UPDATE db_itensmenu SET help = 'Desarquivamento' WHERE id_item = 3435;
            UPDATE db_itensmenu SET help = 'Reimpressão da Capa do Processo' WHERE id_item = 3475;
            UPDATE db_itensmenu SET help = '' WHERE id_item = 3781;
            UPDATE db_itensmenu SET help = 'CGMs corretos' WHERE id_item = 3786;
            UPDATE db_itensmenu SET help = '' WHERE id_item = 3791;
            UPDATE db_itensmenu SET help = 'Relatório de Variáveis' WHERE id_item = 3806;
            UPDATE db_itensmenu SET help = 'Relátorio de Documentos' WHERE id_item = 3807;
            UPDATE db_itensmenu SET help = 'Cancela recibo' WHERE id_item = 3809;
            UPDATE db_itensmenu SET help = '' WHERE id_item = 3812;
            UPDATE db_itensmenu SET help = 'Documentos / Tipo de Processo' WHERE id_item = 3883;
            UPDATE db_itensmenu SET help = 'Duplos no CGM' WHERE id_item = 3909;
            UPDATE db_itensmenu SET help = 'Relatório dos processos' WHERE id_item = 4073;
            UPDATE db_itensmenu SET help = 'Despacho' WHERE id_item = 4079;
            UPDATE db_itensmenu SET help = 'Transferência' WHERE id_item = 4083;
            UPDATE db_itensmenu SET help = 'Recebimento' WHERE id_item = 4098;
            UPDATE db_itensmenu SET help = 'Cancelamento Parcial' WHERE id_item = 4124;
            UPDATE db_itensmenu SET help = 'Cancela Transferência' WHERE id_item = 4131;
            UPDATE db_itensmenu SET help = 'Consistência de CPF/CNPJ' WHERE id_item = 4155;
            UPDATE db_itensmenu SET help = 'Alteração de Despacho' WHERE id_item = 4196;
            UPDATE db_itensmenu SET help = 'Lote' WHERE id_item = 4257;
            UPDATE db_itensmenu SET help = 'Relatório de processos por departamento' WHERE id_item = 4384;
            UPDATE db_itensmenu SET help = 'Inclusão de Ceplocalidades' WHERE id_item = 5714;
            UPDATE db_itensmenu SET help = 'Alteração de Ceplocalidades' WHERE id_item = 5715;
            UPDATE db_itensmenu SET help = 'Exclusão de Ceplocalidades' WHERE id_item = 5716;
            UPDATE db_itensmenu SET help = 'Inclusão de Ceplogradouros' WHERE id_item = 5718;
            UPDATE db_itensmenu SET help = 'Alteração de Ceplogradouros' WHERE id_item = 5719;
            UPDATE db_itensmenu SET help = 'Exclusão de Ceplogradouros' WHERE id_item = 5720;
            UPDATE db_itensmenu SET help = 'Inclusão' WHERE id_item = 7851;
            UPDATE db_itensmenu SET help = 'Alteração' WHERE id_item = 7852;
            UPDATE db_itensmenu SET help = 'Exclusão' WHERE id_item = 7853;
            UPDATE db_itensmenu SET help = 'Inclusão de Cadenderestado' WHERE id_item = 8298;
            UPDATE db_itensmenu SET help = 'Alteração de Cadenderestado' WHERE id_item = 8299;
            UPDATE db_itensmenu SET help = 'Inclusão de Cadendermunicipio' WHERE id_item = 8302;
            UPDATE db_itensmenu SET help = 'Alteração de Cadendermunicipio' WHERE id_item = 8303;
            UPDATE db_itensmenu SET help = 'Incluir novo CGM' WHERE id_item = 8452;
            UPDATE db_itensmenu SET help = 'Alterar Cadastro Geral do Municipio' WHERE id_item = 8453;
            UPDATE db_itensmenu SET help = 'Exclui Cadastro Geral do Município' WHERE id_item = 8454;
            UPDATE db_itensmenu SET help = 'consulta pelo CGM duplo processado' WHERE id_item = 8770;
            UPDATE db_itensmenu SET help = 'Apensar Processo' WHERE id_item = 9224;
            UPDATE db_itensmenu SET help = 'Nova consulta de CGM' WHERE id_item = 9255;
            UPDATE db_itensmenu SET help = 'Anexar Documentos' WHERE id_item = 9852;
            UPDATE db_itensmenu SET help = 'Etiquetas para Processos' WHERE id_item = 9982;
            UPDATE db_itensmenu SET help = 'Etiquetas para Processos' WHERE id_item = 9983;
            UPDATE db_itensmenu SET help = 'CGMs Incluídos/Alterados' WHERE id_item = 29323;
            UPDATE db_itensmenu SET help = 'Tipo de documento do processo.' WHERE id_item = 228316;
            UPDATE db_itensmenu SET help = 'Inclusão de Volumes' WHERE id_item = 228322;
            UPDATE db_itensmenu SET help = 'Alteração de Volume' WHERE id_item = 228323;
            UPDATE db_itensmenu SET help = 'Anexar Documentos ao Volume' WHERE id_item = 228324;
            UPDATE db_itensmenu SET help = 'Tipos dos Processo com as Receitas' WHERE id_item = 437508;
            UPDATE db_itensmenu SET help = 'Inlusão de Despacho' WHERE id_item = 608572;
            UPDATE db_itensmenu SET help = 'Andamento do processo' WHERE id_item = 228068;
        ");
    }
}