version: '2'
services:

  php_ecidade:
    build:
      context: ./docker/php56-apache
    ports:
     - "8881:80"
    volumes:
        - ../:/var/www/html/
  database:
      image: postgres:9.4
      environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: "trust"
          POSTGRES_PASSWORD:
