#!/usr/bin/env bash

set -e
set -x

if [[ -z "${2:-}" ]]; then
  exit 1
fi

TAG=$(echo "${2:-}" | tr [:upper:] [:lower:])

if [[ "${1:-}" == "artisan" ]]; then
  for _B in $(env PGPASSWORD="" psql -A -t -h -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT datname FROM pg_database WHERE datname LIKE 'dbportal_schema_v2_3_57_${TAG}';"); do
    env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '"${_B}"' AND pg_stat_activity.pid <> pg_backend_pid();" > /dev/null 2>&1
    env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "DROP DATABASE ${_B};" > /dev/null 2>&1
  done
  env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'template1' AND pg_stat_activity.pid <> pg_backend_pid();" > /dev/null 2>&1
  env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "CREATE DATABASE dbportal_schema_v2_3_57_${TAG};" > /dev/null 2>&1
  env PGPASSWORD="ecidade" pg_dump -U ecidade -h pgatend.rs.dbseller.com.br -p 5432 dbportal_schema_v2_3_57 | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 dbportal_schema_v2_3_57_${TAG} > /dev/null 2>&1
  echo 'select fc_startsession(); select public.fc_set_pg_search_path();' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_schema_v2_3_57_${TAG} > /dev/null 2>&1
  echo 'VACUUM ANALYZE;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_schema_v2_3_57_${TAG} > /dev/null 2>&1
  for _B in $(env PGPASSWORD="" psql -A -t -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT datname FROM pg_database WHERE datname LIKE 'dbportal_demo_v2_3_57_${TAG}';"); do
    env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '"${_B}"' AND pg_stat_activity.pid <> pg_backend_pid();" > /dev/null 2>&1
    env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "DROP DATABASE ${_B};" > /dev/null 2>&1
  done
  env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'template1' AND pg_stat_activity.pid <> pg_backend_pid();" > /dev/null 2>&1
  env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "CREATE DATABASE dbportal_demo_v2_3_57_${TAG};" > /dev/null 2>&1
  env PGPASSWORD="ecidade" pg_dump -U ecidade -h pgatend.rs.dbseller.com.br -p 5432 dbportal_demo_v2_3_57 | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 dbportal_demo_v2_3_57_${TAG} > /dev/null 2>&1
  echo 'select fc_startsession(); select public.fc_set_pg_search_path();' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_${TAG} > /dev/null 2>&1
  echo 'DROP TABLE IF EXISTS plugins.atualizacaomelhoria CASCADE;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_${TAG} > /dev/null 2>&1
  echo 'TRUNCATE configuracoes.db_plugin CASCADE;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_${TAG} > /dev/null 2>&1
  echo "SELECT fc_grant_revoke('grant', 'plugin', 'select', '%', '%');" | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_${TAG} > /dev/null 2>&1
  echo 'GRANT ALL ON SCHEMA plugins TO plugin;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_${TAG} > /dev/null 2>&1
  echo 'VACUUM ANALYZE;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_${TAG} > /dev/null 2>&1
elif [[ "${1:-}" == "integracao" ]]; then
  for _B in $(env PGPASSWORD="" psql -A -t -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT datname FROM pg_database WHERE datname LIKE 'dbportal_demo_integracao_${TAG}';"); do
    env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '"${_B}"' AND pg_stat_activity.pid <> pg_backend_pid();" > /dev/null 2>&1
    env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "DROP DATABASE ${_B};" > /dev/null 2>&1
  done
  env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'template1' AND pg_stat_activity.pid <> pg_backend_pid();" > /dev/null 2>&1
  env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d postgres -c "CREATE DATABASE dbportal_demo_v2_3_57_integracao_${TAG};" > /dev/null 2>&1
  env PGPASSWORD="ecidade" pg_dump -U ecidade -h pgatend.rs.dbseller.com.br -p 5432 dbportal_demo_v2_3_57 | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 dbportal_demo_v2_3_57_integracao_${TAG} > /dev/null 2>&1
  echo 'select fc_startsession(); select public.fc_set_pg_search_path();' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_integracao_${TAG} > /dev/null 2>&1
  echo 'DROP TABLE IF EXISTS plugins.atualizacaomelhoria CASCADE;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_integracao_${TAG} > /dev/null 2>&1
  echo 'TRUNCATE configuracoes.db_plugin CASCADE;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_integracao_${TAG} > /dev/null 2>&1
  echo "SELECT fc_grant_revoke('grant', 'plugin', 'select', '%', '%');" | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_integracao_${TAG} > /dev/null 2>&1
  echo 'GRANT ALL ON SCHEMA plugins TO plugin;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_integracao_${TAG} > /dev/null 2>&1
  echo 'VACUUM ANALYZE;' | env PGPASSWORD="" psql -U ecidade -h pgs02.rs.dbseller.com.br -p 6433 -d dbportal_demo_v2_3_57_integracao_${TAG} > /dev/null 2>&1
else
  exit 1
fi
