<?php


namespace App\Domain\Financeiro\Orcamento\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class Recurso
 * @package ECidade\Financeiro\Orcamento\Model
 * @property integer $o15_codigo
 * @property string $o15_descr
 * @property string $o15_codtri
 * @property string $o15_finali
 * @property integer $o15_tipo
 * @property Carbon $o15_datalimite
 * @property integer $o15_db_estruturavalor
 * @property string $o15_codigosiconfi
 * @property integer $o15_loaidentificadoruso
 * @property integer $o15_loatipo
 * @property integer $o15_loagrupo
 * @property string $o15_loaespecificacao
 * @property integer $o15_complemento
 * @property string $o15_recurso
 */
class Recurso extends Model
{
    protected $table = 'orcamento.orctiporec';
    protected $primaryKey = 'o15_codigo';
    public $timestamps = false;
    public $incrementing = false;

    protected $dates = [
        'o15_datalimite'
    ];

    protected $casts = [
        'o15_codigo' => 'integer',
        'o15_tipo' => 'integer',
        'o15_db_estruturavalor' => 'integer',
        'o15_loaidentificadoruso' => 'integer',
        'o15_loatipo' => 'integer',
        'o15_loagrupo' => 'integer',
        'o15_complemento' => 'integer',
        'o15_descr' => 'string',
        'o15_codtri' => 'string',
        'o15_finali' => 'string',
        'o15_codigosiconfi' => 'string',
        'o15_loaespecificacao' => 'string',
    ];

    /**
     * @var array
     */
    private $storage = [];

    /**
     * @return int
     */
    public function getCodigo()
    {
        return $this->o15_codigo;
    }

    /**
     * @return string
     */
    public function getDescricao()
    {
        return $this->o15_descr;
    }

    /**
     * @return string
     */
    public function getCodigoTribunal()
    {
        return $this->o15_codtri;
    }

    /**
     * @return string
     */
    public function getFinalidade()
    {
        return $this->o15_finali;
    }

    /**
     * @return int
     */
    public function getTipoRecurso()
    {
        return $this->o15_tipo;
    }

    /**
     * @return Carbon
     */
    public function getDataLimite()
    {
        return $this->o15_datalimite;
    }

    /**
     * @return ValorEstrutural
     */
    public function getDbEstruturaValor()
    {
        if (empty($this->storage['db_estruturavalor'])) {
            $this->storage['db_estruturavalor'] = $this->valorEstrutural;
        }
        return $this->storage['db_estruturavalor'];
    }

    /**
     * @param ValorEstrutural $valorEstrutural
     */
    public function setDbEstruturaValor(ValorEstrutural $valorEstrutural)
    {
        $this->storage['db_estruturavalor'] = $valorEstrutural;
    }

    /**
     * @return string
     */
    public function getCodigoSiconfi()
    {
        return $this->o15_codigosiconfi;
    }

    /**
     * @return int
     */
    public function getLoaIdentificadorUso()
    {
        return $this->o15_loaidentificadoruso;
    }

    /**
     * @return int
     */
    public function getLoaTipo()
    {
        return $this->o15_loatipo;
    }

    /**
     * @return int
     */
    public function getLoaGrupo()
    {
        return $this->o15_loagrupo;
    }

    /**
     * @return string
     */
    public function getLoaEspecificacao()
    {
        return $this->o15_loaespecificacao;
    }

    /**
     * @return Complemento
     */
    public function getComplemento()
    {
        if (empty($this->storage['complemento'])) {
            $this->storage['complemento'] = $this->complemento;
        }

        return $this->storage['complemento'];
    }

    /**
     * @param Complemento $complemento
     */
    public function setComplemento(Complemento $complemento)
    {
        $this->storage['complemento'] = $complemento;
    }


    /**
     * @return int
     */
    public function getRecurso()
    {
        return $this->o15_recurso;
    }

    public function toArray()
    {
        $this->complemento;
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    /**
     * @return BelongsTo
     */
    public function valorEstrutural()
    {
        return $this->belongsTo(ValorEstrutural::class, 'o15_db_estruturavalor', 'db121_sequencial');
    }

    public function complemento()
    {
        return $this->hasOne(Complemento::class, 'o200_sequencial', 'o15_complemento');
    }

    /**
     * @param $query
     * @param Recurso $recurso
     * @return mixed
     */
    public function scopeAlterouCamposCompoeRecurso($query, Recurso $recurso)
    {
        return $query->where('o15_codigo', '=', $recurso->getCodigo())
            ->where(function ($query) use ($recurso) {
                $query->where('o15_recurso', '!=', $recurso->getRecurso())
                    ->orWhere('o15_complemento', '!=', $recurso->getComplemento()->o200_sequencial);
            });
    }

    /**
     * @param $query
     * @param Recurso $recurso
     * @return mixed
     */
    public function scopeRecursoExiste($query, Recurso $recurso)
    {
        $query = $query->when($recurso->getCodigo(), function ($query) use ($recurso) {
            $query->where('o15_codigo', '!=', $recurso->getCodigo());
        })->where('o15_complemento', '=', $recurso->getComplemento()->o200_sequencial)
            ->where('o15_recurso', '=', $recurso->getRecurso());
        return $query ;
    }

    /**
     * @param $query
     * @param Recurso $recurso
     * @return mixed
     */
    public function scopeRecursoJaFoiUsado($query, $codigo)
    {
        $query = $query->where('o15_codigo', '=', $codigo)
            ->whereRaw('
             (exists(select 1 from orcreceita where o70_codigo = o15_codigo) or
              exists(select 1 from orcdotacao where o58_codigo = o15_codigo) or
              exists(select 1 from conplanoreduz where c61_codigo = o15_codigo) or
              exists(select 1 from conplanoorcamentoanalitica where c61_codigo = o15_codigo) or
              exists(select 1 from estimativareceita where recurso_id = o15_codigo) or
              exists(select 1 from conlancamrecurso where c130_orctiporec = o15_codigo) or
              exists(select 1 from detalhamentoiniciativa where pl20_recurso = o15_codigo))
            ');
        return $query ;
    }

    /**
     * Fontes de recurso a partir de 2022
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function fontesRecursos()
    {
        return $this->hasMany(FonteRecurso::class, 'orctiporec_id', 'o15_codigo')
            ->orderBy('exercicio');
    }

    /**
     * @param $exercicio
     * @return FonteRecurso|null
     */
    public function fonteRecurso($exercicio)
    {
        return $this->hasOne(FonteRecurso::class, 'orctiporec_id', 'o15_codigo')
            ->where('exercicio', '=', $exercicio)
            ->first();
    }
}
