<?
$campos = "linhacolunavalorinformacaocomplementar.o157_orcparamseqorcparamseqcoluna,linhacolunavalorinformacaocomplementar.o157_conplanoinfocomplementar,linhacolunavalorinformacaocomplementar.o157_valor,linhacolunavalorinformacaocomplementar.o157_sequencial";
?>
