<?
$campos = "sagresordenadordespesa.c139_sequencial,sagresordenadordespesa.c139_instit,sagresordenadordespesa.c139_cgm,sagresordenadordespesa.c139_cgmsubstituto,sagresordenadordespesa.c139_principal,sagresordenadordespesa.c139_substituto,sagresordenadordespesa.c139_datainicio,sagresordenadordespesa.c139_datafim,sagresordenadordespesa.c139_tipoatojuridico,sagresordenadordespesa.c139_titulo,sagresordenadordespesa.c139_ativo,sagresordenadordespesa.c139_datainatividade,sagresordenadordespesa.c139_idusuario,sagresordenadordespesa.c139_datainiciosub,sagresordenadordespesa.c139_datafimsub";
?>
