select fc_executa_ddl('insert into db_sysarquivo values (3839, ''cgs_und_ext'', ''Extensão do Cadastro Geral da Saúde nas Unidades.'', ''z01'', ''2015-07-13'', ''cgs_und_ext'', 0, ''f'', ''f'', ''f'', ''f'' );');
select fc_executa_ddl('insert into db_sysarqmod values (1000004,3839);');
select fc_executa_ddl('insert into db_syscampo values(21305,\'z01_i_id\',\'int4\',\'Código da extensão do Cadastro Geral da Saúde\',\'0\', \'Código\',10,\'f\',\'f\',\'f\',1,\'text\',\'Código\');');
select fc_executa_ddl('insert into db_syscampo values(21307,\'z01_b_faleceu\',\'bool\',\'Valida se o CGS faleceu.\',\'f\', \'Faleceu\',1,\'t\',\'f\',\'f\',5,\'text\',\'Faleceu\');');
select fc_executa_ddl('insert into db_syscampo values(21308,\'z01_d_falecimento\',\'date\',\'Data do falecimento do CGS.\',\'null\', \'Falecimento\',10,\'t\',\'f\',\'f\',1,\'text\',\'Falecimento\');');
select fc_executa_ddl('insert into db_syscampo values(21309,\'z01_b_descnomemae\',\'bool\',\'Valida se desconhece o nome da mãe.\',\'f\', \'Desconhece o nome da mãe\',1,\'t\',\'f\',\'f\',5,\'text\',\'Desconhece o nome da mãe\');');
select fc_executa_ddl('insert into db_syscampo values(21310,\'z01_i_naturalidade\',\'int4\',\'Naturalidade do CGS.\',\'0\', \'Naturalidade\',10,\'t\',\'f\',\'f\',1,\'text\',\'Naturalidade\');');
select fc_executa_ddl('insert into db_syscampo values(21311,\'z01_i_paisorigem\',\'int4\',\'País de origem do CGS.\',\'0\', \'País de origem\',10,\'t\',\'f\',\'f\',1,\'text\',\'País de origem\');');
select fc_executa_ddl('insert into db_syscampo values(21312,\'z01_v_municnasc\',\'varchar(40)\',\'Município de nascimento do CGS.\',\'\', \'Município de nascimento\',40,\'t\',\'t\',\'f\',0,\'text\',\'Município de nascimento\');');
select fc_executa_ddl('insert into db_syscampo values(21313,\'z01_v_ufnasc\',\'varchar(2)\',\'UF de nascimento do CGS.\',\'\', \'UF de nascimento\',2,\'t\',\'t\',\'f\',0,\'text\',\'UF de nascimento\');');
select fc_executa_ddl('insert into db_syscampo values(21314,\'z01_codigoibgenasc\',\'varchar(50)\',\'Código IBGE do CGM.\',\'\', \'IBGE\',50,\'t\',\'t\',\'f\',0,\'text\',\'IBGE\');');
select fc_executa_ddl('insert into db_syscampo values(21315,\'z01_i_codocupacao\',\'int4\',\'Código de ocupação do CGM.\',\'0\', \'Ocupação\',10,\'t\',\'f\',\'f\',1,\'text\',\'Ocupação\');');
select fc_executa_ddl('insert into db_syscampo values(21316,\'z01_i_escolaridade\',\'int4\',\'Escolaridade do CGS.\',\'0\', \'Escolaridade\',10,\'t\',\'f\',\'f\',1,\'text\',\'Escolaridade\');');
select fc_executa_ddl('insert into db_syscampo values(21317,\'z01_i_cgm\',\'int4\',\'CGM vinculado ao CGS\',\'0\', \'CGM\',10,\'t\',\'f\',\'f\',1,\'text\',\'CGM\');');
select fc_executa_ddl('insert into db_syscampo values(21318,\'z01_i_cge\',\'int4\',\'CGE vinculado ao CGS.\',\'0\', \'CGE\',10,\'t\',\'f\',\'f\',1,\'text\',\'CGE\');');
select fc_executa_ddl('insert into db_syscampo values(21319,\'z01_i_cidadao\',\'int4\',\'Cidadão vínculado ao CGS.\',\'0\', \'Cidadão\',10,\'t\',\'f\',\'f\',1,\'text\',\'Cidadão\');');
select fc_executa_ddl('insert into db_syscampo values(21320,\'z01_b_inativo\',\'bool\',\'Valida cadastro inativo do CGS.\',\'false\', \'Cadastro inativo\',1,\'f\',\'f\',\'f\',5,\'text\',\'Cadastro inativo\');');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21305,1,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,1008844,2,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21307,3,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21308,4,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21309,5,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21310,6,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21311,7,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21312,8,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21313,9,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21314,10,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21315,11,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21316,12,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21317,13,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21318,14,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21319,15,0);');
select fc_executa_ddl('insert into db_sysarqcamp values(3839,21320,16,0);');
select fc_executa_ddl('insert into db_sysprikey (codarq,codcam,sequen,camiden) values(3839,21305,1,21305);');
select fc_executa_ddl('insert into db_sysforkey values(3839,1008844,1,1010144,0);');
select fc_executa_ddl('insert into db_syssequencia values(1000490, ''cgs_und_ext_z01_i_id_seq'', 1, 1, 9223372036854775807, 1, 1);');
select fc_executa_ddl('update db_sysarqcamp set codsequencia = 1000490 where codarq = 3839 and codcam = 21305;');
select fc_executa_ddl('select setval(\'cgs_und_ext_z01_i_id_seq\', (select max(z01_i_id) from cgs_und_ext), true)');