
insert into db_layouttxt values (261, 'IMPORTAÇÃO CNPJS TSE', 0, '', 1 );
insert into db_layoutlinha values (861, 261, 'HEADER', 1, 0, 0, 0, '', '', false );
insert into db_layoutlinha values (862, 261, 'DETALHE', 3, 0, 0, 0, '', '', false );
insert into db_layoutlinha values (863, 261, 'TRAILER', 5, 0, 0, 0, '', '', false );
insert into db_layoutcampos values (14806, 861, 'registro', 'IDENTIFICADOR DO REGISTRO. FIXO 1', 2, 1, '1', 1, true, true, 'd', '', 0 );
insert into db_layoutcampos values (14807, 861, 'data_geracao', 'DATA E HORA DA GERAÇÃO. ', 1, 2, '', 12, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14808, 861, 'versao_leiaute', 'VERSÃO DO ARQUIVO DE CNPJS. FIXO 100', 2, 14, '100', 3, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14809, 861, 'nome_leiaute', 'NOME DO LEIAUTE. FIXO CNPJPREST', 1, 17, 'CNPJPREST', 10, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14810, 861, 'espacos_branco', 'PREENCHIMENTO COM ESPAÇOS EM BRANCO', 1, 27, '', 174, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14811, 862, 'registro', 'IDENTIFICADOR DO REGISTRO. FIXO 2', 2, 1, '2', 1, true, true, 'd', '', 0 );
insert into db_layoutcampos values (14812, 862, 'tipo_prestador_contas', '01 – PARTIDO 02 - CANDIDATO', 2, 2, '', 2, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14813, 862, 'cnpj', 'CNPJ DO PRESTADOR DE CONTAS', 2, 4, '', 14, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14814, 862, 'nome_prestador_contas', 'NOME FISCAL DO PRESTADOR DE CONTAS', 1, 18, '', 150, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14815, 862, 'natureza_juridica', 'NATUREZA JURÍDICA DO CNPJ', 1, 168, '', 4, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14816, 862, 'cnae_principal', 'CÓDIGO NACIONAL DE ATIVIDADE ECONÔMICA', 1, 172, '', 7, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14817, 862, 'espacos_branco', 'PREENCHIDO COM ESPAÇOS EM BRANCO', 1, 179, '', 10, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14818, 862, 'data_insercao_cnpj', 'DATA E HORA DA INSERÇÃO DO CNPJ NO ARQUI', 1, 189, '', 12, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14819, 863, 'registro', 'IDENTIFICADOR DO REGISTRO. FIXO 9', 2, 1, '9', 1, true, true, 'd', '', 0 );
insert into db_layoutcampos values (14820, 863, 'total_cnpjs', 'QUANTIDADE TOTAL DE CNPJ´S  DO ARQUIVO.', 2, 2, '', 9, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14821, 863, 'espacos_branco', 'PREENCHER COM ESPAÇOS EM BRANCO', 1, 11, '', 190, false, true, 'd', '', 0 );

insert into db_layouttxt values (262, 'EXPORTAÇÃO NFES TSE', 0, '', 1 );
insert into db_layoutlinha values (864, 262, 'HEADER', 1, 0, 0, 0, '', '', false );
insert into db_layoutlinha values (865, 262, 'DETALHE', 3, 0, 0, 0, '', '', false );
insert into db_layoutlinha values (866, 262, 'TRAILER', 5, 0, 0, 0, '', '', false );
insert into db_layoutcampos values (14822, 864, 'registro', 'IDENTIFICADOR DO REGISTRO HEADER. FIXO 1', 2, 1, '1', 1, true, true, 'd', '', 0 );
insert into db_layoutcampos values (14823, 864, 'uf', 'UF DA PREFEITURA, GOVERNO OU SEFAZ', 1, 2, '', 2, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14824, 864, 'cnpj', 'CNPJ DA PREFEITURA, GOVERNO OU SEFAZ', 1, 4, '', 14, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14825, 864, 'data_processamento', 'DATA DO PROCESSAMENTO', 1, 18, '', 8, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14826, 864, 'numero_notificacao', 'NUMERO NOTIFICAÇÃO GERADA PELO TSE', 1, 26, '', 10, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14827, 864, 'numero_remessa', 'ANO E MÊS REFERENTE À GERAÇÃO DA REMESSA', 1, 36, '', 6, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14828, 864, 'numero_lote_remessa', 'NÚMERO IDENTIFICADOR DO LOTE DA REMESSA', 1, 42, '', 4, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14829, 864, 'numero_remessa_correcao', 'ANO E MÊS REFERENTE À REMESSA CORRIGIDA', 1, 46, '', 6, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14830, 864, 'numero_lote_remessa_correcao', 'NUM DO LOTE DA REMESSA A SER CORRIGIDA', 1, 52, '', 4, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14831, 864, 'versao_leiaute', 'VERSÃO DO ARQUIVO DE NFES. FIXO 110', 2, 56, '110', 3, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14832, 864, 'nome_leiaute', 'NOME DO LEIAUTE. FIXO ATSENFE', 1, 59, 'ATSENFE', 7, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14833, 864, 'espaco_branco', 'PREENCHER COM ESPAÇOS EM BRANCO', 1, 66, '', 331, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14834, 865, 'registro', 'IDENTIFICADOR DO REGISTRO', 2, 1, '2', 1, true, true, 'd', '', 0 );
insert into db_layoutcampos values (14835, 865, 'uf', 'UF DA NOTA FISCAL', 1, 2, '', 2, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14836, 865, 'cnpj_destinatario', 'CNPJ DO CANDIDATO/DIREÇÃO PARTIDÁRIA', 1, 4, '', 14, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14837, 865, 'tipo_pessoa_emitente', 'FÍSICA (F) OU JURÍDICA (J)', 1, 18, '', 1, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14838, 865, 'cnpj_cpf_emitente', 'NÚMERO DO CNPJ OU CPF DO EMITENTE', 1, 19, '', 14, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14839, 865, 'natureza_operacao', 'VENDA, SERVIÇO OU DOAÇÃO', 1, 33, '', 4, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14840, 865, 'modelo_nota_fiscal', 'CÓDIGO QUE IDENTIFICA O MODELO DA NF', 1, 37, '', 2, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14841, 865, 'data_emissao', 'DATA DE EMISSÃO DA NOTA FISCAL', 1, 39, '', 8, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14842, 865, 'serie_nfe', 'SÉRIE DA NOTA FISCAL', 1, 47, '', 3, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14843, 865, 'numero_nfe', 'NÚMERO DA NOTA FISCAL', 1, 50, '', 15, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14844, 865, 'numero_nfe_substituida', 'NÚMERO DA NF SUBSTITUÍDA OU CANCELADA', 1, 65, '', 15, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14845, 865, 'valor_total_nfe', 'VALOR TOTAL DA NOTA FISCAL', 1, 80, '', 17, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14846, 865, 'chave_acesso_nfe', 'CHAVE DE ACESSO DA NOTA FISCAL', 1, 97, '', 50, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14847, 865, 'url_acesso_nfe', 'ENDEREÇO ELETRÔNICO PARA ACESSO À NFE', 1, 147, '', 250, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14848, 866, 'registro', 'IDENTIFICADOR DO REGISTRO. FIXO 9', 2, 1, '9', 1, true, true, 'd', '', 0 );
insert into db_layoutcampos values (14849, 866, 'total_nfe', 'TOTAL DE NFES PRESENTES NO LOTE', 1, 2, '', 9, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14850, 866, 'checksum', 'CÁLCULO DE TODAS AS LINHAS DO DETALHE', 1, 11, '', 32, false, true, 'd', '', 0 );
insert into db_layoutcampos values (14851, 866, 'espaco_branco', 'PREENCHER COM ESPAÇOS EM BRANCO', 1, 43, '', 354, false, true, 'd', '', 0 );
