<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class M22866PlDecretoReducaoOrcamentoReceitaDespesa extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = <<<SQL

drop function if exists fc_lancam_suplementacao(integer,date,integer);
create or replace function fc_lancam_suplementacao(integer,date,integer)
returns varchar(80)
as
$$
DECLARE

  CODSUP 	ALIAS FOR $1;
  DATA 		ALIAS FOR $2;
  ID_USUARIO 	ALIAS FOR $3;

  SUPLEM 	RECORD;
  PROCESSADO	BOOLEAN DEFAULT FALSE;
  REDUCAO	BOOLEAN DEFAULT FALSE;
  SALDO		FLOAT8 DEFAULT 0;

  CODLAN	INTEGER;
  CODDOCRED	FLOAT8;
  LANCAMENTO  	RECORD;
  CODSEQ	      INTEGER;
  TEMMES	      INTEGER;
  DIF1          FLOAT8 DEFAULT 0;
  DIF2          FLOAT8 DEFAULT 0;
  DIFERENCA     FLOAT8;
  ARRECADMAIOR  FLOAT8;
  V_PROCURA_DOT	INTEGER DEFAULT 0;

  TIPOSUP  INTEGER;
  VLR_RECEITA FLOAT8 DEFAULT 0;

  RET INTEGER;
BEGIN

  -- VERIFICA SE ESTA PROCESSADA OU NAO
  SELECT O49_CODSUP
  INTO CODLAN
  FROM ORCSUPLEMLAN
  WHERE O49_CODSUP = CODSUP;
  IF NOT CODLAN IS NULL THEN
     RETURN '9 SUPLEMENTACAO JA PROCESSADA';
  END IF;

   select o46_tiposup
     into TIPOSUP
     from ORCSUPLEM where o46_codsup = CODSUP;

  --conlancam
  --conlancamsup
  --conlancamdot
  --conlancamdoc



  RET := 0;
  -- CASO FOR REDUCAO VERIFICAR SE TEM RESERVA DE SALDO DAS MESMAS E RETIRA-LA E DEPOIS VERIFICAR SE TEM SALDO A REDUZIR
  FOR SUPLEM IN
        SELECT O80_CODDOT,O80_CODRES
        FROM ORCSUPLEM
	        INNER JOIN ORCSUPLEMVAL ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
       		inner JOIN ORCRESERVASUP ON O81_CODSUP = ORCSUPLEM.O46_CODSUP
		      inner JOIN ORCRESERVA ON O80_CODRES = ORCRESERVASUP.O81_CODRES AND O80_CODDOT = ORCSUPLEMVAL.O47_CODDOT
        WHERE O46_CODSUP = CODSUP  AND O47_VALOR < 0 LOOP

        REDUCAO := TRUE;
        IF SUPLEM.O80_CODDOT IS NULL   THEN
           RETURN '32 REDUCAO SEM RESERVA DE SALDO';
        END IF;
        IF SUPLEM.O80_CODRES IS NULL  THEN
           RETURN '2 DOTACAO ('|| SUPLEM.O80_CODDOT ||') SEM RESERVA DE SALDO';
        END IF;

        -- DELETE AS RESERVAS DE SALDO
        DELETE FROM ORCRESERVASUP WHERE O81_CODRES = SUPLEM.O80_CODRES;
        DELETE FROM ORCRESERVA    WHERE O80_CODRES = SUPLEM.O80_CODRES;

        RET := 1;
  END LOOP;

  -- TESTA SE OA VALORES QUANDO REDUCAO ESTAO IGUAIS
  SELECT O48_CODDOCRED
  INTO CODDOCRED
  FROM ORCSUPLEM
       INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
  WHERE O46_CODSUP = CODSUP;


  IF CODDOCRED != NULL OR CODDOCRED != 0 THEN

     SELECT ROUND(SUM(O47_VALOR),2)::float8 AS O47_VALOR
     INTO DIFERENCA
     FROM ORCSUPLEM
     	  INNER JOIN ORCSUPLEMVAL ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
     WHERE O46_CODSUP = CODSUP;



     if TIPOSUP = 1050 then

         SELECT ROUND(SUM(o85_valor),2)::float8 AS o85_valor
         INTO VLR_RECEITA
          FROM ORCSUPLEM
          join orcsuplemrec on o85_codsup = o46_codsup
         where O46_CODSUP = CODSUP;
         DIFERENCA := DIFERENCA + VLR_RECEITA;
      --VLR_RECEITA
      raise notice 'TIPO:  %  ,  DIFERENCA: %', TIPOSUP, DIFERENCA;
     end if;





     -- - IF CODDOCRED != 0 THEN
     if DIFERENCA  != 0 then

        RETURN '3 SUPLEMENTACAO ('|| CODSUP ||') LANCADA COM VALORES INCONSISTENTES.';

     END IF;

  END IF;





  -- VERIFICA ARRECADAÇÃO A MAIOR, SE O VALOR DA RECEITA ESTA COMPATIVEL COM O VALOR SUPLEMENTADO
  SELECT O48_ARRECADMAIOR
  INTO ARRECADMAIOR
  FROM ORCSUPLEM
       INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
  WHERE O46_CODSUP = CODSUP;
  IF (ARRECADMAIOR != NULL OR ARRECADMAIOR != 0) AND (TIPOSUP != 1050) THEN

      SELECT  sum(coalesce(O47_VALOR,0))
      INTO DIF1
      FROM ORCSUPLEM
     	   LEFT JOIN ORCSUPLEMVAL ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
      WHERE O46_CODSUP = CODSUP;

      SELECT  sum(coalesce(o85_valor,0))
      INTO DIF2
      FROM ORCSUPLEM
         LEFT JOIN ORCSUPLEMREC ON O85_CODSUP = O46_CODSUP
      WHERE O46_CODSUP = CODSUP;

      DIFERENCA := round(DIF1-DIF2, 2);

      --raise notice ' valor %,%,%',DIFERENCA,dif1,dif2;
      IF  cast(DIFERENCA as numeric)  != cast(0 as numeric) THEN

         RETURN '3 ARRECADACAO A MAIOR, POREM RECEITA NAO LANCADA. CODSUP:('|| CODSUP ||')';

      END IF;

  END IF;






  FOR SUPLEM IN
      SELECT O46_CODSUP,O46_DATA,
             O47_CODSUP, ABS(O47_VALOR)::FLOAT8 AS O47_VALOR,
             CASE WHEN O47_VALOR >= 0 THEN  ORCSUPLEMTIPO.O48_CODDOCSUP  ELSE ORCSUPLEMTIPO.O48_CODDOCRED  END AS TIPO,
		         O47_ANOUSU,
		         O47_CODDOT,
		         O48_CODDOCSUP,
		         O48_CODDOCRED
      FROM ORCSUPLEM
	        INNER JOIN ORCSUPLEMVAL  ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
	        INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
      WHERE O46_CODSUP = CODSUP LOOP


        PROCESSADO := TRUE;

        SELECT O59_MES
        INTO TEMMES
        FROM ORCDOTACAOVAL
        WHERE O59_ANOUSU = SUPLEM.O47_ANOUSU AND
              O59_CODDOT = SUPLEM.O47_CODDOT AND
             O59_CODDOC = SUPLEM.TIPO AND
   	    O59_MES    = TO_CHAR(DATA,'MM')::integer;

        IF TEMMES IS NULL THEN

            SELECT 	O58_CODDOT
          	INTO V_PROCURA_DOT
       	  	FROM ORCDOTACAO
        		WHERE O58_ANOUSU = SUPLEM.O47_ANOUSU AND
 			          O58_CODDOT = SUPLEM.O47_CODDOT;

            IF V_PROCURA_DOT IS NULL THEN
               RETURN '55 - DOTACAO ' || SUPLEM.O47_CODDOT || ' NAO CADASTRADA NO ORCDOTACAO NO ANO ' || SUPLEM.O47_ANOUSU;
         	  END IF;

            INSERT INTO ORCDOTACAOVAL (O59_ANOUSU,O59_CODDOT,O59_CODDOC,O59_MES,O59_VALOR)
            VALUES (SUPLEM.O47_ANOUSU,SUPLEM.O47_CODDOT,SUPLEM.TIPO,TO_CHAR(DATA,'MM')::INTEGER,SUPLEM.O47_VALOR);

       ELSE

          UPDATE ORCDOTACAOVAL SET O59_VALOR = (O59_VALOR + SUPLEM.O47_VALOR)
          WHERE O59_ANOUSU = SUPLEM.O47_ANOUSU AND
                O59_CODDOT = SUPLEM.O47_CODDOT AND
                O59_CODDOC = SUPLEM.TIPO AND
	              O59_MES    = TO_CHAR(DATA,'MM')::INTEGER;
       END IF;

  END LOOP;

  -- processamento da receita quando for arrecadacao a maior

  FOR SUPLEM IN SELECT O85_CODREC, O85_VALOR, O85_ANOUSU, O48_ARRECADMAIOR
                FROM ORCSUPLEMREC
                     INNER JOIN ORCSUPLEM     ON ORCSUPLEM.O46_CODSUP  = ORCSUPLEMREC.O85_CODSUP
	                   INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
                WHERE O85_CODSUP = CODSUP LOOP

                IF SUPLEM.O48_ARRECADMAIOR IS NULL OR SUPLEM.O48_ARRECADMAIOR  = 0 THEN

                  RETURN '5 - DOCUMENTO DE LANCAMENTO DA RECEITA NAO CADASTRADO';

                ELSE

                  SELECT O71_MES
                  INTO TEMMES
                  FROM ORCRECEITAVAL
                  WHERE O71_ANOUSU = SUPLEM.O85_ANOUSU AND
                        O71_CODREC = SUPLEM.O85_CODREC AND
     	                  O71_CODDOC = SUPLEM.O48_ARRECADMAIOR AND
	                      O71_MES    = TO_CHAR(DATA,'MM')::integer;

                  IF TEMMES IS NULL THEN
                  	  INSERT INTO ORCRECEITAVAL (O71_ANOUSU,O71_CODREC,O71_CODDOC,O71_MES,O71_VALOR)
                      VALUES (SUPLEM.O85_ANOUSU,SUPLEM.O85_CODREC,SUPLEM.O48_ARRECADMAIOR,TO_CHAR(DATA,'MM')::INTEGER,SUPLEM.O85_VALOR);

                  ELSE

                  	  UPDATE ORCRECEITAVAL SET O71_VALOR = ROUND(O71_VALOR + SUPLEM.O85_VALOR,2)::float8
                  	  WHERE O71_ANOUSU = SUPLEM.O85_ANOUSU AND
                         		O71_CODREC = SUPLEM.O85_CODREC AND
                        		O71_CODDOC = SUPLEM.O48_ARRECADMAIOR AND
                        		O71_MES    = TO_CHAR(DATA,'MM')::INTEGER;

                  END IF;

               END IF;

  END LOOP;





  IF PROCESSADO IS FALSE THEN
     RETURN '0 SUPLEMENTACAO NAO PROCESSADA SEM VALOR LANCADO.';
  ELSE

     INSERT INTO ORCSUPLEMLAN (O49_CODSUP,O49_DATA,O49_ID_USUARIO) VALUES (CODSUP,DATA,ID_USUARIO);

     RETURN '1 SUPLEMENTACAO PROCESSADA.';
  END IF;

END;
$$ language plpgsql;




SQL;
DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = <<<SQL


drop function if exists fc_lancam_suplementacao(integer,date,integer);
create or replace function fc_lancam_suplementacao(integer,date,integer)
returns varchar(80)
as
$$
DECLARE

  CODSUP 	ALIAS FOR $1;
  DATA 		ALIAS FOR $2;
  ID_USUARIO 	ALIAS FOR $3;

  SUPLEM 	RECORD;
  PROCESSADO	BOOLEAN DEFAULT FALSE;
  REDUCAO	BOOLEAN DEFAULT FALSE;
  SALDO		FLOAT8 DEFAULT 0;

  CODLAN	INTEGER;
  CODDOCRED	FLOAT8;
  LANCAMENTO  	RECORD;
  CODSEQ	      INTEGER;
  TEMMES	      INTEGER;
  DIF1          FLOAT8 DEFAULT 0;
  DIF2          FLOAT8 DEFAULT 0;
  DIFERENCA     FLOAT8;
  ARRECADMAIOR  FLOAT8;
  V_PROCURA_DOT	INTEGER DEFAULT 0;

  TIPOSUP  INTEGER;
  VLR_RECEITA FLOAT8 DEFAULT 0;

  RET INTEGER;
BEGIN

  -- VERIFICA SE ESTA PROCESSADA OU NAO
  SELECT O49_CODSUP
  INTO CODLAN
  FROM ORCSUPLEMLAN
  WHERE O49_CODSUP = CODSUP;
  IF NOT CODLAN IS NULL THEN
     RETURN '9 SUPLEMENTACAO JA PROCESSADA';
  END IF;

   select o46_tiposup
     into TIPOSUP
     from ORCSUPLEM where o46_codsup = CODSUP;

  --conlancam
  --conlancamsup
  --conlancamdot
  --conlancamdoc



  RET := 0;
  -- CASO FOR REDUCAO VERIFICAR SE TEM RESERVA DE SALDO DAS MESMAS E RETIRA-LA E DEPOIS VERIFICAR SE TEM SALDO A REDUZIR
  FOR SUPLEM IN
        SELECT O80_CODDOT,O80_CODRES
        FROM ORCSUPLEM
	        INNER JOIN ORCSUPLEMVAL ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
       		inner JOIN ORCRESERVASUP ON O81_CODSUP = ORCSUPLEM.O46_CODSUP
		      inner JOIN ORCRESERVA ON O80_CODRES = ORCRESERVASUP.O81_CODRES AND O80_CODDOT = ORCSUPLEMVAL.O47_CODDOT
        WHERE O46_CODSUP = CODSUP  AND O47_VALOR < 0 LOOP

        REDUCAO := TRUE;
        IF SUPLEM.O80_CODDOT IS NULL   THEN
           RETURN '32 REDUCAO SEM RESERVA DE SALDO';
        END IF;
        IF SUPLEM.O80_CODRES IS NULL  THEN
           RETURN '2 DOTACAO ('|| SUPLEM.O80_CODDOT ||') SEM RESERVA DE SALDO';
        END IF;

        -- DELETE AS RESERVAS DE SALDO
        DELETE FROM ORCRESERVASUP WHERE O81_CODRES = SUPLEM.O80_CODRES;
        DELETE FROM ORCRESERVA    WHERE O80_CODRES = SUPLEM.O80_CODRES;

        RET := 1;
  END LOOP;

  -- TESTA SE OA VALORES QUANDO REDUCAO ESTAO IGUAIS
  SELECT O48_CODDOCRED
  INTO CODDOCRED
  FROM ORCSUPLEM
       INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
  WHERE O46_CODSUP = CODSUP;


  IF CODDOCRED != NULL OR CODDOCRED != 0 THEN

     SELECT ROUND(SUM(O47_VALOR),2)::float8 AS O47_VALOR
     INTO DIFERENCA
     FROM ORCSUPLEM
     	  INNER JOIN ORCSUPLEMVAL ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
     WHERE O46_CODSUP = CODSUP;








     -- - IF CODDOCRED != 0 THEN
     if DIFERENCA  != 0 then

        RETURN '3 SUPLEMENTACAO ('|| CODSUP ||') LANCADA COM VALORES INCONSISTENTES.';

     END IF;

  END IF;





  -- VERIFICA ARRECADAÇÃO A MAIOR, SE O VALOR DA RECEITA ESTA COMPATIVEL COM O VALOR SUPLEMENTADO
  SELECT O48_ARRECADMAIOR
  INTO ARRECADMAIOR
  FROM ORCSUPLEM
       INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
  WHERE O46_CODSUP = CODSUP;
  IF (ARRECADMAIOR != NULL OR ARRECADMAIOR != 0) THEN

      SELECT  sum(coalesce(O47_VALOR,0))
      INTO DIF1
      FROM ORCSUPLEM
     	   LEFT JOIN ORCSUPLEMVAL ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
      WHERE O46_CODSUP = CODSUP;

      SELECT  sum(coalesce(o85_valor,0))
      INTO DIF2
      FROM ORCSUPLEM
         LEFT JOIN ORCSUPLEMREC ON O85_CODSUP = O46_CODSUP
      WHERE O46_CODSUP = CODSUP;

      DIFERENCA := round(DIF1-DIF2, 2);

      --raise notice ' valor %,%,%',DIFERENCA,dif1,dif2;
      IF  cast(DIFERENCA as numeric)  != cast(0 as numeric) THEN

         RETURN '3 ARRECADACAO A MAIOR, POREM RECEITA NAO LANCADA. CODSUP:('|| CODSUP ||')';

      END IF;

  END IF;






  FOR SUPLEM IN
      SELECT O46_CODSUP,O46_DATA,
             O47_CODSUP, ABS(O47_VALOR)::FLOAT8 AS O47_VALOR,
             CASE WHEN O47_VALOR >= 0 THEN  ORCSUPLEMTIPO.O48_CODDOCSUP  ELSE ORCSUPLEMTIPO.O48_CODDOCRED  END AS TIPO,
		         O47_ANOUSU,
		         O47_CODDOT,
		         O48_CODDOCSUP,
		         O48_CODDOCRED
      FROM ORCSUPLEM
	        INNER JOIN ORCSUPLEMVAL  ON ORCSUPLEM.O46_CODSUP = ORCSUPLEMVAL.O47_CODSUP
	        INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
      WHERE O46_CODSUP = CODSUP LOOP


        PROCESSADO := TRUE;

        SELECT O59_MES
        INTO TEMMES
        FROM ORCDOTACAOVAL
        WHERE O59_ANOUSU = SUPLEM.O47_ANOUSU AND
              O59_CODDOT = SUPLEM.O47_CODDOT AND
             O59_CODDOC = SUPLEM.TIPO AND
   	    O59_MES    = TO_CHAR(DATA,'MM')::integer;

        IF TEMMES IS NULL THEN

            SELECT 	O58_CODDOT
          	INTO V_PROCURA_DOT
       	  	FROM ORCDOTACAO
        		WHERE O58_ANOUSU = SUPLEM.O47_ANOUSU AND
 			          O58_CODDOT = SUPLEM.O47_CODDOT;

            IF V_PROCURA_DOT IS NULL THEN
               RETURN '55 - DOTACAO ' || SUPLEM.O47_CODDOT || ' NAO CADASTRADA NO ORCDOTACAO NO ANO ' || SUPLEM.O47_ANOUSU;
         	  END IF;

            INSERT INTO ORCDOTACAOVAL (O59_ANOUSU,O59_CODDOT,O59_CODDOC,O59_MES,O59_VALOR)
            VALUES (SUPLEM.O47_ANOUSU,SUPLEM.O47_CODDOT,SUPLEM.TIPO,TO_CHAR(DATA,'MM')::INTEGER,SUPLEM.O47_VALOR);

       ELSE

          UPDATE ORCDOTACAOVAL SET O59_VALOR = (O59_VALOR + SUPLEM.O47_VALOR)
          WHERE O59_ANOUSU = SUPLEM.O47_ANOUSU AND
                O59_CODDOT = SUPLEM.O47_CODDOT AND
                O59_CODDOC = SUPLEM.TIPO AND
	              O59_MES    = TO_CHAR(DATA,'MM')::INTEGER;
       END IF;

  END LOOP;

  -- processamento da receita quando for arrecadacao a maior

  FOR SUPLEM IN SELECT O85_CODREC, O85_VALOR, O85_ANOUSU, O48_ARRECADMAIOR
                FROM ORCSUPLEMREC
                     INNER JOIN ORCSUPLEM     ON ORCSUPLEM.O46_CODSUP  = ORCSUPLEMREC.O85_CODSUP
	                   INNER JOIN ORCSUPLEMTIPO ON ORCSUPLEM.O46_TIPOSUP = ORCSUPLEMTIPO.O48_TIPOSUP
                WHERE O85_CODSUP = CODSUP LOOP

                IF SUPLEM.O48_ARRECADMAIOR IS NULL OR SUPLEM.O48_ARRECADMAIOR  = 0 THEN

                  RETURN '5 - DOCUMENTO DE LANCAMENTO DA RECEITA NAO CADASTRADO';

                ELSE

                  SELECT O71_MES
                  INTO TEMMES
                  FROM ORCRECEITAVAL
                  WHERE O71_ANOUSU = SUPLEM.O85_ANOUSU AND
                        O71_CODREC = SUPLEM.O85_CODREC AND
     	                  O71_CODDOC = SUPLEM.O48_ARRECADMAIOR AND
	                      O71_MES    = TO_CHAR(DATA,'MM')::integer;

                  IF TEMMES IS NULL THEN
                  	  INSERT INTO ORCRECEITAVAL (O71_ANOUSU,O71_CODREC,O71_CODDOC,O71_MES,O71_VALOR)
                      VALUES (SUPLEM.O85_ANOUSU,SUPLEM.O85_CODREC,SUPLEM.O48_ARRECADMAIOR,TO_CHAR(DATA,'MM')::INTEGER,SUPLEM.O85_VALOR);

                  ELSE

                  	  UPDATE ORCRECEITAVAL SET O71_VALOR = ROUND(O71_VALOR + SUPLEM.O85_VALOR,2)::float8
                  	  WHERE O71_ANOUSU = SUPLEM.O85_ANOUSU AND
                         		O71_CODREC = SUPLEM.O85_CODREC AND
                        		O71_CODDOC = SUPLEM.O48_ARRECADMAIOR AND
                        		O71_MES    = TO_CHAR(DATA,'MM')::INTEGER;

                  END IF;

               END IF;

  END LOOP;





  IF PROCESSADO IS FALSE THEN
     RETURN '0 SUPLEMENTACAO NAO PROCESSADA SEM VALOR LANCADO.';
  ELSE

     INSERT INTO ORCSUPLEMLAN (O49_CODSUP,O49_DATA,O49_ID_USUARIO) VALUES (CODSUP,DATA,ID_USUARIO);

     RETURN '1 SUPLEMENTACAO PROCESSADA.';
  END IF;

END;
$$ language plpgsql;



SQL;
        DB::connection()->getPdo()->exec($sql);
    }
}
