;para usar o ambientede produção do Regin, descomente a linha abaixo
;webservice_url=http://reginrj.jucerja.rj.gov.br:8080/SiarcoWeb/RecebeDadosService
;para usar o ambiente de homologação do Regin, descomente a linha abaixo
webservice_url=http://reginrj.jucerja.rj.gov.br:8081/SiarcoWeb/RecebeDadosService